-- Hito 2 · Banco de preguntas, plantilla de evaluación y criterios genéricos.
-- Ver docs/07-DICCIONARIO-DE-DATOS.md y docs/08-ALCANCE-DEL-MVP.md (Hito 2).
-- Los bancos son repositorios, no cuestionarios que se apliquen enteros (RF-47):
-- cada vacante arma su propia versión de evaluación eligiendo de aquí.

-- Las 22 dimensiones que puede medir una pregunta. Catálogo cerrado.
CREATE TABLE dimension (
    codigo         text PRIMARY KEY,
    nombre         text NOT NULL,
    definicion     text NOT NULL,
    es_obligatoria boolean NOT NULL,
    orden          integer NOT NULL,
    creado_en      timestamptz NOT NULL DEFAULT now()
);

-- Una versión publicada del banco. organizacion_id vacío = biblioteca global de Renaser,
-- por eso es la única raíz con esa columna opcional.
CREATE TABLE version_banco (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id          bigint REFERENCES organizacion(id),
    tipo_banco               text NOT NULL CHECK (tipo_banco IN ('NIVEL', 'ALINEACION')),
    nivel_puesto_codigo      text REFERENCES nivel_puesto(codigo),
    etiqueta                 text NOT NULL,
    estado                   text NOT NULL CHECK (estado IN ('BORRADOR', 'PUBLICADA')),
    publicada_por_usuario_id bigint REFERENCES usuario(id),
    publicada_en             timestamptz,
    creado_en                timestamptz NOT NULL DEFAULT now()
);

-- logica_interna nunca llega al portal (RF-53). es_puntuable es false en ESTILO y
-- CONSISTENCIA: no suman, solo describen o generan alertas (RF-54).
CREATE TABLE pregunta (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_banco_id bigint NOT NULL REFERENCES version_banco(id),
    codigo           text NOT NULL,
    bloque           text,
    tipo             text NOT NULL
        CHECK (tipo IN ('ESTILO', 'SITUACION', 'CONDUCTUAL', 'MICROCASO', 'DILEMA', 'CONSISTENCIA')),
    enunciado        text NOT NULL,
    situacion        text,
    logica_interna   text,
    es_puntuable     boolean NOT NULL,
    orden            integer NOT NULL,
    creado_en        timestamptz NOT NULL DEFAULT now(),
    UNIQUE (version_banco_id, codigo)
);

-- puntaje nullable a propósito: en ESTILO no hay clave, y en SITUACION a veces solo se
-- define cuál es la opción buena.
CREATE TABLE opcion (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pregunta_id bigint NOT NULL REFERENCES pregunta(id),
    letra       text NOT NULL,
    texto       text NOT NULL,
    puntaje     numeric(5,2),
    creado_en   timestamptz NOT NULL DEFAULT now(),
    UNIQUE (pregunta_id, letra)
);

-- Cuánto suma cada opción a cada dimensión que toca (típico: 2 la principal, 1 una
-- secundaria). Sin id: la llave es la combinación.
CREATE TABLE opcion_dimension (
    opcion_id        bigint NOT NULL REFERENCES opcion(id),
    dimension_codigo text NOT NULL REFERENCES dimension(codigo),
    incremento       numeric(5,2) NOT NULL,
    creado_en        timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (opcion_id, dimension_codigo)
);

-- Qué dimensión mide una pregunta abierta, que no tiene opciones que puntuar.
CREATE TABLE pregunta_dimension (
    pregunta_id      bigint NOT NULL REFERENCES pregunta(id),
    dimension_codigo text NOT NULL REFERENCES dimension(codigo),
    creado_en        timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (pregunta_id, dimension_codigo)
);

-- Qué dos preguntas se comparan para detectar contradicciones (RF-63). Arranca vacía:
-- el cliente nunca dijo qué pregunta va con cuál.
CREATE TABLE par_consistencia (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_banco_id  bigint NOT NULL REFERENCES version_banco(id),
    pregunta_a_id     bigint NOT NULL REFERENCES pregunta(id),
    pregunta_b_id     bigint NOT NULL REFERENCES pregunta(id),
    diferencia_maxima numeric(5,2) NOT NULL,
    creado_en         timestamptz NOT NULL DEFAULT now(),
    UNIQUE (pregunta_a_id, pregunta_b_id)
);

-- La "receta": qué combinación de preguntas arma la evaluación de un nivel y familia.
CREATE TABLE plantilla_evaluacion (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id          bigint NOT NULL REFERENCES organizacion(id),
    nombre                   text NOT NULL,
    nivel_puesto_codigo      text NOT NULL REFERENCES nivel_puesto(codigo),
    familia_codigo           text REFERENCES familia(codigo),
    version                  integer NOT NULL,
    estado                   text NOT NULL CHECK (estado IN ('BORRADOR', 'PUBLICADA')),
    minutos_objetivo         integer NOT NULL,
    vigencia_meses           integer NOT NULL,
    publicada_por_usuario_id bigint REFERENCES usuario(id),
    publicada_en             timestamptz,
    creado_en                timestamptz NOT NULL DEFAULT now(),
    UNIQUE (organizacion_id, nombre, version)
);

-- Cuántas preguntas de cada tipo/dimensión le tocan a esta plantilla.
-- tipo_pregunta y dimension_codigo nullable = no importa cuál, solo la cantidad.
CREATE TABLE cuota_plantilla_evaluacion (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plantilla_evaluacion_id bigint NOT NULL REFERENCES plantilla_evaluacion(id),
    tipo_banco              text NOT NULL CHECK (tipo_banco IN ('NIVEL', 'ALINEACION')),
    tipo_pregunta           text
        CHECK (tipo_pregunta IS NULL OR tipo_pregunta IN
            ('ESTILO', 'SITUACION', 'CONDUCTUAL', 'MICROCASO', 'DILEMA', 'CONSISTENCIA')),
    dimension_codigo        text REFERENCES dimension(codigo),
    cantidad_min            integer NOT NULL,
    cantidad_max            integer NOT NULL,
    creado_en               timestamptz NOT NULL DEFAULT now(),
    CHECK (cantidad_min <= cantidad_max)
);

-- Los criterios genéricos "para cualquier etapa" que deja preparados el hito 1. Los del
-- CV (hito 2) no llevan version_plantilla_prueba_id; los de la prueba del puesto (hito 3)
-- sí, pero esa tabla todavía no existe, así que la columna va sin FK por ahora.
-- NULLS NOT DISTINCT evita que los criterios globales del CV se dupliquen sin querer.
CREATE TABLE criterio (
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo                      text NOT NULL,
    nombre                      text NOT NULL,
    descripcion                 text,
    etapa_codigo                text NOT NULL REFERENCES etapa(codigo),
    version_plantilla_prueba_id bigint,
    puntos                      numeric(5,2),
    metodo_verificacion         text NOT NULL CHECK (metodo_verificacion IN ('SISTEMA', 'AGENTE', 'PERSONA')),
    orden                       integer NOT NULL,
    creado_en                   timestamptz NOT NULL DEFAULT now(),
    UNIQUE NULLS NOT DISTINCT (codigo, version_plantilla_prueba_id)
);

-- Cierra la FK que V5 dejó suelta a propósito ("su tabla llega en el hito 2").
ALTER TABLE vacante
    ADD CONSTRAINT vacante_plantilla_evaluacion_fk
    FOREIGN KEY (plantilla_evaluacion_id) REFERENCES plantilla_evaluacion(id);

CREATE INDEX pregunta_version_banco_idx ON pregunta (version_banco_id);
CREATE INDEX opcion_pregunta_idx ON opcion (pregunta_id);
CREATE INDEX cuota_plantilla_idx ON cuota_plantilla_evaluacion (plantilla_evaluacion_id);
CREATE INDEX criterio_etapa_idx ON criterio (etapa_codigo);

-- ============ Las 22 dimensiones (13 obligatorias) ============
INSERT INTO dimension (codigo, nombre, definicion, es_obligatoria, orden) VALUES
    ('INT',  'Integridad',                 'Actúa igual con o sin supervisión',                          true,  1),
    ('OWN',  'Sentido de dueño',           'Se responsabiliza del resultado, no solo de la tarea',       true,  2),
    ('INI',  'Iniciativa',                 'Actúa antes de que se lo pidan',                             true,  3),
    ('CRI',  'Pensamiento crítico',        'Cuestiona supuestos y busca evidencia',                      true,  4),
    ('SER',  'Orientación a servicio',     'Prioriza la necesidad de la persona a la que atiende',       false, 5),
    ('COM',  'Comunicación',               'Se explica con claridad, escrito y hablado',                 true,  6),
    ('CTL',  'Control de personas',        'Supervisa y da seguimiento al trabajo de otros',             false, 7),
    ('SUP',  'Supervisión diferenciada',   'Ajusta el nivel de seguimiento según la persona y la tarea', false, 8),
    ('PRI',  'Priorización',               'Distingue lo urgente de lo importante',                      true,  9),
    ('DEC',  'Toma de decisiones',         'Decide con la información disponible, sin parálisis',        true,  10),
    ('VEL',  'Velocidad de ejecución',     'Entrega en el tiempo esperado',                              false, 11),
    ('LRN',  'Velocidad de aprendizaje',   'Incorpora retroalimentación y mejora rápido',                true,  12),
    ('SYS',  'Sistemas y procesos',        'Crea o mejora procesos, no solo los sigue',                  true,  13),
    ('QUA',  'Calidad de la evidencia',    'Lo que dice se puede verificar',                             true,  14),
    ('REL',  'Relación con el equipo',     'Colabora y resuelve fricción sin escalar todo',              false, 15),
    ('AUT',  'Autogobierno',               'Regula su propio trabajo sin que lo empujen',                true,  16),
    ('PPL',  'Desarrollo de personas',     'Forma o hace crecer a otros',                                false, 17),
    ('BUS',  'Visión de negocio',          'Conecta su trabajo con el resultado de Renaser',             false, 18),
    ('POT',  'Potencial',                  'Capacidad de crecer más allá del puesto actual',             true,  19),
    ('SELF', 'Autoconocimiento',           'Reconoce sus propios límites y errores',                     true,  20),
    ('VAL',  'Alineación de valores',      'Lo que valora coincide con lo que hace Renaser',             true,  21),
    ('FIT',  'Encaje con el puesto',       'Sus fortalezas coinciden con lo que el puesto exige',        true,  22);
