-- Hito 2 · Los agentes de IA y los pesos que reparten la nota del Perfil Integral.
-- Ver docs/07-DICCIONARIO-DE-DATOS.md. RF-144 a RF-150: qué guarda cada ejecución,
-- interfaz abstracta de proveedor, y que un fallo técnico nunca se guarda como un cero.

-- Los 9 agentes. Catálogo cerrado, sin id: el código es la llave.
CREATE TABLE agente (
    codigo      text PRIMARY KEY
        CHECK (codigo IN ('NECESIDAD_TALENTO', 'CAZATALENTOS', 'EVIDENCIA_CV', 'EVALUADOR',
                           'POTENCIAL_RIESGO', 'PRUEBA_PUESTO', 'SIMULACION', 'DESEMPENO', 'APRENDIZAJE')),
    nombre      text NOT NULL,
    descripcion text NOT NULL,
    version     integer NOT NULL,
    es_activo   boolean NOT NULL DEFAULT true,
    creado_en   timestamptz NOT NULL DEFAULT now()
);

-- La instrucción vigente de cada agente. Solo una activa por agente a la vez.
CREATE TABLE instruccion_ia (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agente_codigo            text NOT NULL REFERENCES agente(codigo),
    version                  integer NOT NULL,
    texto                    text NOT NULL,
    es_activa                boolean NOT NULL DEFAULT false,
    publicada_por_usuario_id bigint REFERENCES usuario(id),
    publicada_en             timestamptz,
    creado_en                timestamptz NOT NULL DEFAULT now(),
    UNIQUE (agente_codigo, version)
);

CREATE UNIQUE INDEX instruccion_ia_activa_unica_idx
    ON instruccion_ia (agente_codigo) WHERE es_activa;

-- La cola de trabajo. Regla 3 del doc 03: si la IA falla se reintenta, nunca se
-- inventa una nota. referencia_tabla/referencia_id NO son FK: cada agente escribe
-- sobre una tabla distinta (postulacion, evaluacion, etc).
CREATE TABLE trabajo_ia (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id  bigint NOT NULL REFERENCES organizacion(id),
    agente_codigo    text NOT NULL REFERENCES agente(codigo),
    postulacion_id   bigint REFERENCES postulacion(id),
    referencia_tabla text,
    referencia_id    bigint,
    estado           text NOT NULL CHECK (estado IN ('PENDIENTE', 'EN_CURSO', 'TERMINADO', 'FALLIDO')),
    intentos         integer NOT NULL DEFAULT 0,
    terminado_en     timestamptz,
    creado_en        timestamptz NOT NULL DEFAULT now()
);

-- Cada llamada real al modelo, auditable. ~1,5 GB/año esperado (ver diccionario).
CREATE TABLE ejecucion_ia (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trabajo_ia_id     bigint NOT NULL REFERENCES trabajo_ia(id),
    organizacion_id   bigint NOT NULL REFERENCES organizacion(id),
    agente_codigo     text NOT NULL REFERENCES agente(codigo),
    version_agente    integer NOT NULL,
    objetivo          text NOT NULL,
    modelo            text NOT NULL,
    proveedor         text NOT NULL,
    version_modelo    text,
    instruccion_ia_id bigint REFERENCES instruccion_ia(id),
    envio             text NOT NULL,
    respuesta         text,
    confianza         numeric(5,2),
    tokens_entrada    integer,
    tokens_salida     integer,
    costo             numeric(10,4),
    duracion_ms       integer,
    es_exitosa        boolean NOT NULL,
    error             text,
    creado_en         timestamptz NOT NULL DEFAULT now()
);

-- Cuánto pesa cada dimensión y cada criterio del CV, por nivel de puesto. Igual que
-- peso_etapa: que sumen lo esperado lo comprueba el código al publicar, no la base.
CREATE TABLE peso_dimension (
    version_pesos_id    bigint NOT NULL REFERENCES version_pesos(id),
    nivel_puesto_codigo text NOT NULL REFERENCES nivel_puesto(codigo),
    dimension_codigo    text NOT NULL REFERENCES dimension(codigo),
    peso                numeric(5,2) NOT NULL,
    creado_en           timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (version_pesos_id, nivel_puesto_codigo, dimension_codigo)
);

CREATE TABLE peso_criterio (
    version_pesos_id    bigint NOT NULL REFERENCES version_pesos(id),
    nivel_puesto_codigo text NOT NULL REFERENCES nivel_puesto(codigo),
    criterio_id         bigint NOT NULL REFERENCES criterio(id),
    peso                numeric(5,2) NOT NULL,
    creado_en           timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (version_pesos_id, nivel_puesto_codigo, criterio_id)
);

CREATE INDEX trabajo_ia_postulacion_idx ON trabajo_ia (postulacion_id);
CREATE INDEX trabajo_ia_pendiente_idx ON trabajo_ia (creado_en) WHERE estado = 'PENDIENTE';
CREATE INDEX ejecucion_ia_trabajo_idx ON ejecucion_ia (trabajo_ia_id);
CREATE INDEX ejecucion_ia_creado_idx ON ejecucion_ia (creado_en);

-- ============ Los 9 agentes, versión inicial ============
INSERT INTO agente (codigo, nombre, descripcion, version, es_activo) VALUES
    ('NECESIDAD_TALENTO', 'Necesidad de talento',      'Evalúa si una Solicitud de Talento está bien sustentada', 1, true),
    ('CAZATALENTOS',      'Cazatalentos',               'Arma preguntas de verificación desde el currículum',      1, true),
    ('EVIDENCIA_CV',      'Evidencia del currículum',   'Clasifica cada afirmación del CV y puntúa los 8 criterios', 1, true),
    ('EVALUADOR',         'Evaluador',                  'Califica las respuestas abiertas de la evaluación',       1, true),
    ('POTENCIAL_RIESGO',  'Potencial y riesgo',         'Arma el Perfil de Talento y los 4 grupos de prioridad',   1, true),
    ('PRUEBA_PUESTO',     'Prueba del puesto',          'Califica los entregables de la prueba (hito 3)',          1, true),
    ('SIMULACION',        'Simulación de trabajo',      'Apoya la calificación de la simulación (hito 3)',         1, true),
    ('DESEMPENO',         'Desempeño',                  'Sigue el desempeño a 90 días (fuera del MVP)',            1, true),
    ('APRENDIZAJE',       'Aprendizaje',                'Detecta patrones entre calificación de IA y de persona', 1, true);
