-- Hito 2 · La evaluación de un candidato y el Perfil Integral que resulta de calificarla.
-- Ver docs/03-ESTADOS-POSTULACION.md (etapa Perfil Integral) y docs/01, RF-47 a RF-69.

-- Cuelga del usuario, no de la postulación: la misma evaluación se puede reutilizar en
-- otra vacante si sigue vigente (RF-70, fuera del MVP, pero el modelo ya lo admite).
CREATE TABLE evaluacion (
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id             bigint NOT NULL REFERENCES organizacion(id),
    usuario_id                  bigint NOT NULL REFERENCES usuario(id),
    plantilla_evaluacion_id     bigint NOT NULL REFERENCES plantilla_evaluacion(id),
    version_banco_nivel_id      bigint NOT NULL REFERENCES version_banco(id),
    version_banco_alineacion_id bigint REFERENCES version_banco(id),
    reutiliza_de_evaluacion_id  bigint REFERENCES evaluacion(id),
    estado                      text NOT NULL CHECK (estado IN ('PENDIENTE', 'EN_CURSO', 'TERMINADA', 'VENCIDA')),
    vence_en                    timestamptz,
    iniciada_en                 timestamptz,
    terminada_en                timestamptz,
    vigente_hasta                timestamptz,
    creado_en                   timestamptz NOT NULL DEFAULT now()
);

-- Cierra la FK que V6 dejó suelta a propósito ("su tabla llega en el hito 2").
ALTER TABLE postulacion
    ADD CONSTRAINT postulacion_evaluacion_fk
    FOREIGN KEY (evaluacion_id) REFERENCES evaluacion(id);

-- Congela qué preguntas le tocaron a esta evaluación y en qué orden (RF-51): así se
-- puede reproducir el examen exacto que vio el candidato.
CREATE TABLE orden_pregunta (
    evaluacion_id  bigint NOT NULL REFERENCES evaluacion(id),
    pregunta_id    bigint NOT NULL REFERENCES pregunta(id),
    posicion       integer NOT NULL,
    orden_opciones text NOT NULL,
    creado_en      timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (evaluacion_id, pregunta_id),
    UNIQUE (evaluacion_id, posicion)
);

-- Cada respuesta se guarda al momento (RF-52). Solo se puede responder una pregunta
-- que de verdad le tocó a esta evaluación: por eso la FK compuesta contra orden_pregunta.
CREATE TABLE respuesta (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluacion_id  bigint NOT NULL REFERENCES evaluacion(id),
    pregunta_id    bigint NOT NULL REFERENCES pregunta(id),
    opcion_id      bigint REFERENCES opcion(id),
    texto          text,
    segundos       integer,
    respondida_en  timestamptz NOT NULL,
    creado_en      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (evaluacion_id, pregunta_id),
    FOREIGN KEY (evaluacion_id, pregunta_id) REFERENCES orden_pregunta (evaluacion_id, pregunta_id)
);

-- La calificación de una respuesta abierta. explicacion NUNCA es opcional (RF-56, RF-150):
-- una nota sin explicación no se guarda.
CREATE TABLE nota_respuesta (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    respuesta_id           bigint NOT NULL REFERENCES respuesta(id),
    puntaje                numeric(5,2) NOT NULL CHECK (puntaje BETWEEN 0 AND 4),
    explicacion            text NOT NULL,
    evidencia_citada       text,
    confianza              numeric(5,2),
    ejecucion_ia_id        bigint REFERENCES ejecucion_ia(id),
    ajustada_por_usuario_id bigint REFERENCES usuario(id),
    motivo_ajuste          text,
    ajustada_en            timestamptz,
    creado_en              timestamptz NOT NULL DEFAULT now(),
    UNIQUE (respuesta_id),
    CHECK (ajustada_por_usuario_id IS NULL OR (motivo_ajuste IS NOT NULL AND btrim(motivo_ajuste) <> ''))
);

-- El semáforo de los tres bloques de alineación personal (RF-59 a RF-62). Un rojo no
-- descarta a nadie por sí solo.
CREATE TABLE resultado_alineacion (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluacion_id bigint NOT NULL REFERENCES evaluacion(id),
    bloque        text NOT NULL CHECK (bloque IN ('DINERO', 'MADUREZ', 'AUTOGOBIERNO')),
    semaforo      text NOT NULL CHECK (semaforo IN ('VERDE', 'AMBAR', 'ROJO')),
    explicacion   text,
    creado_en     timestamptz NOT NULL DEFAULT now(),
    UNIQUE (evaluacion_id, bloque)
);

-- Contradicciones detectadas (RF-63, RF-64). Nunca descartan solas: quedan en la ficha
-- como pregunta para la conversación final.
CREATE TABLE alerta (
    id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postulacion_id            bigint NOT NULL REFERENCES postulacion(id),
    tipo                      text NOT NULL CHECK (tipo IN ('CONTRADICCION', 'DEMASIADO_IDEAL')),
    descripcion               text NOT NULL,
    pregunta_a_id             bigint REFERENCES pregunta(id),
    pregunta_b_id             bigint REFERENCES pregunta(id),
    ejecucion_ia_id           bigint REFERENCES ejecucion_ia(id),
    confirmada_por_usuario_id bigint REFERENCES usuario(id),
    creado_en                 timestamptz NOT NULL DEFAULT now()
);

-- El resultado no es una nota: es un retrato (RF-65). confianza_evidencia siempre
-- obligatoria — es lo que le dice al equipo cuánto fiarse del resto del perfil.
CREATE TABLE perfil_talento (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postulacion_id      bigint NOT NULL REFERENCES postulacion(id),
    adecuacion          numeric(5,2),
    potencial           numeric(5,2),
    alto_rendimiento    numeric(5,2),
    confianza_evidencia numeric(5,2) NOT NULL,
    resumen             text,
    version_pesos_id    bigint NOT NULL REFERENCES version_pesos(id),
    ejecucion_ia_id     bigint REFERENCES ejecucion_ia(id),
    actualizado_en      timestamptz NOT NULL DEFAULT now(),
    creado_en           timestamptz NOT NULL DEFAULT now(),
    UNIQUE (postulacion_id)
);

-- Los cuatro tipos de hallazgo, que la Regla 1 del doc 03 prohíbe mezclar.
CREATE TABLE hallazgo_perfil (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfil_talento_id bigint NOT NULL REFERENCES perfil_talento(id),
    tipo             text NOT NULL
        CHECK (tipo IN ('FORTALEZA', 'RIESGO_CRITICO', 'RIESGO_DESARROLLABLE', 'PREFERENCIA', 'FALTA_EVIDENCIA')),
    descripcion      text NOT NULL,
    evidencia        text,
    es_canalizable   boolean NOT NULL DEFAULT false,
    sugerencia       text,
    creado_en        timestamptz NOT NULL DEFAULT now()
);

-- Puede sugerir otro puesto o familia, pero la sugerencia no mueve la postulación (RF-67).
CREATE TABLE sugerencia_puesto (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfil_talento_id bigint NOT NULL REFERENCES perfil_talento(id),
    puesto_id         bigint REFERENCES puesto(id),
    familia_codigo    text REFERENCES familia(codigo),
    motivo            text NOT NULL,
    ejecucion_ia_id   bigint REFERENCES ejecucion_ia(id),
    creado_en         timestamptz NOT NULL DEFAULT now()
);

-- La nota de cada criterio genérico para esta postulación (RF-43: los 8 del currículum
-- en el hito 2). explicacion obligatoria, igual que nota_respuesta.
CREATE TABLE nota_criterio (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postulacion_id          bigint NOT NULL REFERENCES postulacion(id),
    criterio_id             bigint NOT NULL REFERENCES criterio(id),
    puntaje                 numeric(5,2) NOT NULL,
    explicacion             text NOT NULL,
    origen                  text NOT NULL CHECK (origen IN ('AUTOMATICO', 'AGENTE', 'PERSONA')),
    confianza               numeric(5,2),
    ejecucion_ia_id         bigint REFERENCES ejecucion_ia(id),
    calificada_por_usuario_id bigint REFERENCES usuario(id),
    ajustada_por_usuario_id bigint REFERENCES usuario(id),
    motivo_ajuste           text,
    ajustada_en             timestamptz,
    creado_en               timestamptz NOT NULL DEFAULT now(),
    UNIQUE (postulacion_id, criterio_id),
    CHECK (ajustada_por_usuario_id IS NULL OR (motivo_ajuste IS NOT NULL AND btrim(motivo_ajuste) <> ''))
);

-- Cada afirmación del currículum, clasificada (RF-45). El currículum no descarta a
-- nadie por sí solo (RF-46): esto solo alimenta el Perfil Integral.
CREATE TABLE afirmacion_cv (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cv_id               bigint NOT NULL REFERENCES cv(id),
    texto               text NOT NULL,
    clasificacion       text NOT NULL CHECK (clasificacion IN ('DEMOSTRADA', 'DECLARADA', 'CONTRADICHA', 'FALTA_INFO')),
    pregunta_validacion text,
    ejecucion_ia_id     bigint REFERENCES ejecucion_ia(id),
    creado_en           timestamptz NOT NULL DEFAULT now()
);

-- El 40/30/15/15 de peso_etapa aplicado a esta postulación en concreto, atado a la
-- versión de pesos con que se calculó (nunca se recalcula con una versión nueva, RF-139).
CREATE TABLE nota_etapa (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postulacion_id   bigint NOT NULL REFERENCES postulacion(id),
    etapa_codigo     text NOT NULL REFERENCES etapa(codigo),
    puntaje          numeric(5,2) NOT NULL,
    version_pesos_id bigint NOT NULL REFERENCES version_pesos(id),
    calculada_en     timestamptz NOT NULL DEFAULT now(),
    creado_en        timestamptz NOT NULL DEFAULT now(),
    UNIQUE (postulacion_id, etapa_codigo)
);

CREATE INDEX evaluacion_usuario_vigente_idx ON evaluacion (usuario_id, vigente_hasta);
CREATE INDEX respuesta_evaluacion_idx ON respuesta (evaluacion_id);
CREATE INDEX alerta_postulacion_idx ON alerta (postulacion_id);
CREATE INDEX hallazgo_perfil_idx ON hallazgo_perfil (perfil_talento_id);
CREATE INDEX nota_criterio_postulacion_idx ON nota_criterio (postulacion_id);
CREATE INDEX afirmacion_cv_idx ON afirmacion_cv (cv_id);
CREATE INDEX nota_etapa_postulacion_idx ON nota_etapa (postulacion_id);

-- ============ Los 13 permisos nuevos del hito 2 ============
-- En lenguaje normal, como manda el doc 04. Mismo grupo EVALUACION que confirmar_avance
-- del hito 1; CONFIGURACION para lo que solo administra Dirección.
INSERT INTO permiso (codigo, etiqueta, grupo, orden) VALUES
    ('ver_perfil_integral',        'Ver el Perfil Integral de un candidato',        'EVALUACION',    2),
    ('ver_respuestas_evaluacion',  'Ver respuesta por respuesta de la evaluación',  'EVALUACION',    3),
    ('ver_explicacion_ia',         'Ver por qué la IA puso cada nota',              'EVALUACION',    4),
    ('ver_alertas',                'Ver las alertas de contradicción',              'EVALUACION',    5),
    ('confirmar_avance_por_lote',  'Confirmar el avance de varios candidatos a la vez', 'EVALUACION', 6),
    ('ver_claves_puntuacion',      'Ver las claves de puntuación de las preguntas', 'EVALUACION',    7),
    ('ajustar_nota',               'Ajustar a mano una nota puesta por la IA',      'EVALUACION',    8),
    ('elegir_plantilla_evaluacion','Elegir qué plantilla de evaluación se aplica',  'EVALUACION',    9),
    ('editar_banco_preguntas',     'Editar el banco de preguntas',                  'CONFIGURACION', 6),
    ('publicar_version_banco',     'Publicar una versión del banco de preguntas',   'CONFIGURACION', 7),
    ('editar_plantillas_evaluacion','Crear o editar plantillas de evaluación',      'CONFIGURACION', 8),
    ('publicar_version_pesos',     'Cambiar los pesos y publicar una versión nueva','CONFIGURACION', 9),
    ('editar_instrucciones_ia',    'Editar las instrucciones de un agente de IA',   'CONFIGURACION', 10);

-- ============ Quién puede cada permiso nuevo, y con qué alcance ============
-- Derivado del doc 04: Dirección aprueba/publica todo; Talento opera pero no publica lo
-- estructural (banco, pesos, instrucciones son solo de Dirección); Responsable de área
-- solo ve lo de sus vacantes, y nunca claves de puntuación ni ajustes.
INSERT INTO rol_permiso (rol_id, permiso_id, alcance)
SELECT r.id, p.id, x.alcance
FROM (VALUES
    -- Equipo de Talento: opera el día a día, no publica lo estructural
    ('TALENTO', 'ver_perfil_integral',         'TODO'),
    ('TALENTO', 'ver_respuestas_evaluacion',   'TODO'),
    ('TALENTO', 'ver_explicacion_ia',          'TODO'),
    ('TALENTO', 'ver_alertas',                 'TODO'),
    ('TALENTO', 'confirmar_avance_por_lote',   'TODO'),
    ('TALENTO', 'ver_claves_puntuacion',       'TODO'),
    ('TALENTO', 'ajustar_nota',                'TODO'),
    ('TALENTO', 'elegir_plantilla_evaluacion', 'TODO'),
    ('TALENTO', 'editar_banco_preguntas',      'TODO'),
    ('TALENTO', 'editar_plantillas_evaluacion','TODO'),
    -- Responsable del área: solo ve lo de sus vacantes, nunca claves ni ajustes
    ('RESPONSABLE_AREA', 'ver_perfil_integral',         'SUS_VACANTES'),
    ('RESPONSABLE_AREA', 'ver_respuestas_evaluacion',   'SUS_VACANTES'),
    ('RESPONSABLE_AREA', 'ver_explicacion_ia',          'SUS_VACANTES'),
    ('RESPONSABLE_AREA', 'ver_alertas',                 'SUS_VACANTES'),
    ('RESPONSABLE_AREA', 'elegir_plantilla_evaluacion', 'SUS_VACANTES'),
    -- Dirección: todo lo de Talento más lo que solo ella publica
    ('DIRECCION', 'ver_perfil_integral',          'TODO'),
    ('DIRECCION', 'ver_respuestas_evaluacion',    'TODO'),
    ('DIRECCION', 'ver_explicacion_ia',           'TODO'),
    ('DIRECCION', 'ver_alertas',                  'TODO'),
    ('DIRECCION', 'confirmar_avance_por_lote',    'TODO'),
    ('DIRECCION', 'ver_claves_puntuacion',        'TODO'),
    ('DIRECCION', 'ajustar_nota',                 'TODO'),
    ('DIRECCION', 'elegir_plantilla_evaluacion',  'TODO'),
    ('DIRECCION', 'editar_banco_preguntas',       'TODO'),
    ('DIRECCION', 'publicar_version_banco',       'TODO'),
    ('DIRECCION', 'editar_plantillas_evaluacion', 'TODO'),
    ('DIRECCION', 'publicar_version_pesos',       'TODO'),
    ('DIRECCION', 'editar_instrucciones_ia',      'TODO')
) AS x(rol_codigo, permiso_codigo, alcance)
JOIN rol r ON r.codigo = x.rol_codigo
JOIN permiso p ON p.codigo = x.permiso_codigo
WHERE r.organizacion_id = (SELECT id FROM organizacion WHERE codigo = 'RENASER');
