-- Hito 3 · La prueba del puesto y la decisión final.
-- Ver docs/01-REQUISITOS-FUNCIONALES.md §6 y §9, docs/07-DICCIONARIO-DE-DATOS.md §14 y §16.
--
-- Deliberadamente fuera de esta migración: Simulación de trabajo (7 tablas) y Validación
-- práctica. docs/08-ALCANCE-DEL-MVP.md las excluye del MVP por razones no técnicas —
-- logística de sesiones con cupo la primera, una figura contractual que Renaser no ha
-- definido la segunda. También fuera: Evaluador de Estándar (`evaluador_estandar`,
-- `opinion_evaluador_estandar`), que el propio documento recomienda dejar para cuando
-- exista simulación. Ninguna de las tres bloquea lo que sí entra aquí.

-- ============================================================================
-- 1 · La plantilla de prueba
-- ============================================================================

CREATE TABLE plantilla_prueba (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id bigint NOT NULL REFERENCES organizacion(id),
    puesto_id       bigint REFERENCES puesto(id),
    nombre          text NOT NULL,
    es_activa       boolean NOT NULL DEFAULT true,
    creado_en       timestamptz NOT NULL DEFAULT now()
);

-- Si tiene vacante_id, es una copia privada de esa vacante (RF-74 permite personalizar
-- sin tocar la plantilla base). El cambio inesperado ya no tiene minuto fijo: hay un
-- rango y se sortea uno concreto al empezar, para que el segundo candidato no lo sepa.
CREATE TABLE version_plantilla_prueba (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plantilla_prueba_id      bigint NOT NULL REFERENCES plantilla_prueba(id),
    vacante_id               bigint REFERENCES vacante(id),
    version                  integer NOT NULL,
    enunciado                text NOT NULL,
    materiales               text,
    herramientas_permitidas  text,
    modalidad                text NOT NULL CHECK (modalidad IN ('CRONOMETRADA', 'PLAZO_ABIERTO')),
    duracion_minutos         integer,
    plazo_dias               integer,
    minuto_cambio_min        integer,
    minuto_cambio_max        integer,
    minutos_extra            integer,
    estado                   text NOT NULL CHECK (estado IN ('BORRADOR', 'PUBLICADA')),
    publicada_por_usuario_id bigint REFERENCES usuario(id),
    publicada_en             timestamptz,
    creado_en                timestamptz NOT NULL DEFAULT now(),
    UNIQUE (plantilla_prueba_id, version),
    CHECK (modalidad != 'CRONOMETRADA' OR duracion_minutos IS NOT NULL),
    CHECK (modalidad != 'PLAZO_ABIERTO' OR plazo_dias IS NOT NULL),
    CHECK (minuto_cambio_min IS NULL OR minuto_cambio_max IS NULL
           OR minuto_cambio_min <= minuto_cambio_max)
);

CREATE TABLE variante_cambio (
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_plantilla_prueba_id bigint NOT NULL REFERENCES version_plantilla_prueba(id),
    texto                       text NOT NULL,
    orden                       integer NOT NULL,
    creado_en                   timestamptz NOT NULL DEFAULT now(),
    UNIQUE (version_plantilla_prueba_id, orden)
);

-- El catálogo de preguntas: previas (antes de producir), universales (8-10 por
-- plantilla) y específicas del puesto (3-5). Ya no son 17 fijas para todos (RF-83).
CREATE TABLE pregunta_prueba (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo    text NOT NULL UNIQUE,
    enunciado text NOT NULL,
    tipo      text NOT NULL CHECK (tipo IN ('PREVIA', 'UNIVERSAL', 'ESPECIFICA')),
    puesto_id bigint REFERENCES puesto(id),
    revela    text,
    orden     integer NOT NULL,
    creado_en timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE pregunta_version_plantilla (
    version_plantilla_prueba_id bigint NOT NULL REFERENCES version_plantilla_prueba(id),
    pregunta_prueba_id          bigint NOT NULL REFERENCES pregunta_prueba(id),
    orden                       integer NOT NULL,
    creado_en                   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (version_plantilla_prueba_id, pregunta_prueba_id)
);

-- Antes esto era texto libre en la plantilla y el sistema no podía decir «falta el
-- video». Una fila por entregable distinto, cada uno con su propia regla.
CREATE TABLE entregable_requerido (
    id                           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_plantilla_prueba_id  bigint NOT NULL REFERENCES version_plantilla_prueba(id),
    nombre                       text NOT NULL,
    detalle                      text NOT NULL,
    formato                      text NOT NULL CHECK (formato IN ('ARCHIVO', 'ENLACE', 'CUALQUIERA')),
    es_obligatorio               boolean NOT NULL,
    orden                        integer NOT NULL,
    creado_en                    timestamptz NOT NULL DEFAULT now(),
    UNIQUE (version_plantilla_prueba_id, orden)
);

-- ============================================================================
-- 2 · Cuando un candidato rinde
-- ============================================================================

-- El reloj lo lleva el servidor. vence_en se calcula y se guarda al empezar, no se
-- recalcula cada vez: así el barrido de relojes agotados es una consulta indexada, y
-- no depende de que la plantilla siga igual. No hay pausas: cerrar la página no para
-- el reloj. Cuando se acaba, el sistema entrega solo (es_entrega_automatica).
CREATE TABLE intento_prueba (
    id                           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postulacion_id               bigint NOT NULL REFERENCES postulacion(id),
    version_plantilla_prueba_id  bigint NOT NULL REFERENCES version_plantilla_prueba(id),
    iniciado_en                  timestamptz,
    vence_en                     timestamptz,
    entregado_en                 timestamptz,
    es_entrega_automatica        boolean NOT NULL DEFAULT false,
    variante_cambio_id           bigint REFERENCES variante_cambio(id),
    minuto_cambio                integer,
    cambio_mostrado_en           timestamptz,
    creado_en                    timestamptz NOT NULL DEFAULT now(),
    UNIQUE (postulacion_id)
);

CREATE TABLE entregable (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intento_prueba_id       bigint NOT NULL REFERENCES intento_prueba(id),
    entregable_requerido_id bigint NOT NULL REFERENCES entregable_requerido(id),
    archivo_id              bigint REFERENCES archivo(id),
    enlace                  text,
    version                 integer NOT NULL,
    subido_en               timestamptz NOT NULL DEFAULT now(),
    UNIQUE (intento_prueba_id, entregable_requerido_id, version),
    CHECK (archivo_id IS NOT NULL OR enlace IS NOT NULL)
);

CREATE TABLE respuesta_prueba (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intento_prueba_id   bigint NOT NULL REFERENCES intento_prueba(id),
    pregunta_prueba_id  bigint NOT NULL REFERENCES pregunta_prueba(id),
    texto               text NOT NULL,
    respondida_en       timestamptz NOT NULL DEFAULT now(),
    UNIQUE (intento_prueba_id, pregunta_prueba_id)
);

CREATE INDEX version_plantilla_prueba_plantilla_idx ON version_plantilla_prueba (plantilla_prueba_id);
CREATE INDEX pregunta_version_plantilla_pregunta_idx ON pregunta_version_plantilla (pregunta_prueba_id);
CREATE INDEX entregable_requerido_version_idx ON entregable_requerido (version_plantilla_prueba_id);
CREATE INDEX entregable_intento_idx ON entregable (intento_prueba_id);
CREATE INDEX respuesta_prueba_intento_idx ON respuesta_prueba (intento_prueba_id);

-- El barrido que cierra intentos vencidos es una consulta directa sobre una columna
-- indexada: no depende de recorrer toda la tabla ni de recalcular nada.
CREATE INDEX intento_prueba_vence_idx ON intento_prueba (vence_en) WHERE entregado_en IS NULL;

-- Cierra la FK que V5 dejó suelta a propósito ("su tabla llega en el hito 3").
ALTER TABLE vacante
    ADD CONSTRAINT vacante_version_plantilla_prueba_fk
    FOREIGN KEY (version_plantilla_prueba_id) REFERENCES version_plantilla_prueba(id);

-- ============================================================================
-- 3 · Barreras críticas y decisión
-- ============================================================================

-- Antes era un catálogo por nivel. Ahora las define cada vacante; las del nivel se
-- cargan como valores iniciales que se pueden cambiar (docs/07 §5).
CREATE TABLE barrera_critica (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vacante_id  bigint NOT NULL REFERENCES vacante(id),
    descripcion text NOT NULL,
    es_activa   boolean NOT NULL DEFAULT true,
    creado_en   timestamptz NOT NULL DEFAULT now()
);

-- El semáforo final. Cinco valores, no cuatro: "sin datos" es distinto de rojo -falta
-- evidencia, no falla la persona-, y "reserva" es distinto de los dos -la persona vale,
-- pero para otra cosa-.
CREATE TABLE decision (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postulacion_id           bigint NOT NULL REFERENCES postulacion(id),
    semaforo                 text NOT NULL CHECK (semaforo IN ('VERDE', 'AMBAR', 'ROJO', 'SIN_DATOS', 'RESERVA')),
    nota_global              numeric(5,2),
    version_pesos_id         bigint NOT NULL REFERENCES version_pesos(id),
    decidida_por_usuario_id  bigint REFERENCES usuario(id),
    motivo                   text,
    decidida_en              timestamptz,
    creado_en                timestamptz NOT NULL DEFAULT now(),
    UNIQUE (postulacion_id),
    -- Obligatorio cuando decide una persona; el sistema puede proponer sin uno todavía
    CHECK (decidida_por_usuario_id IS NULL OR (motivo IS NOT NULL AND btrim(motivo) <> ''))
);

-- La puede detectar la máquina, pero mientras confirmada_por_usuario_id esté vacío no
-- bloquea a nadie (RF-116).
CREATE TABLE barrera_detectada (
    id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postulacion_id            bigint NOT NULL REFERENCES postulacion(id),
    barrera_critica_id        bigint NOT NULL REFERENCES barrera_critica(id),
    explicacion               text NOT NULL,
    ejecucion_ia_id           bigint REFERENCES ejecucion_ia(id),
    confirmada_por_usuario_id bigint REFERENCES usuario(id),
    confirmada_en             timestamptz,
    descartada_en             timestamptz,
    creado_en                 timestamptz NOT NULL DEFAULT now(),
    UNIQUE (postulacion_id, barrera_critica_id)
);

-- Lo que se pide cuando sale ámbar. El tope (parametro.tope_rondas_evidencia, ya
-- sembrado en 2) impide que una postulación dé vueltas para siempre.
CREATE TABLE evidencia_adicional (
    id                         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postulacion_id             bigint NOT NULL REFERENCES postulacion(id),
    numero                     integer NOT NULL,
    motivo                     text NOT NULL,
    enunciado                  text NOT NULL,
    solicitada_por_usuario_id  bigint NOT NULL REFERENCES usuario(id),
    entregada_en               timestamptz,
    puntaje                    numeric(5,2),
    explicacion                text,
    creado_en                  timestamptz NOT NULL DEFAULT now(),
    UNIQUE (postulacion_id, numero)
);

CREATE INDEX barrera_critica_vacante_idx ON barrera_critica (vacante_id);
CREATE INDEX barrera_detectada_postulacion_idx ON barrera_detectada (postulacion_id);
CREATE INDEX evidencia_adicional_postulacion_idx ON evidencia_adicional (postulacion_id);

-- ============================================================================
-- 4 · Una versión de pesos que reparte lo que falta
-- ============================================================================
-- La v2 (hito 2) sigue teniendo las cinco etapas: 40/30/15/15, con las dos últimas sin
-- nada que las alimente. RF-114 exige que la vacante tenga una versión aprobada ANTES
-- de que empiecen los candidatos, nunca redistribuir a mano por persona. Así que esto
-- crea una v3 con solo las dos etapas que este hito construye, repartiendo
-- proporcionalmente los 30 puntos de Simulación y Validación entre Perfil Integral y
-- Prueba del puesto -docs/08-ALCANCE-DEL-MVP.md, Decisión 5, recomienda repartir en vez
-- de mostrar 70 sobre 100-. Es un cambio de datos: cuando existan las dos etapas que
-- faltan, se crea una v4 y las vacantes migran a ella, sin tocar código.
INSERT INTO version_pesos (organizacion_id, etiqueta, estado, publicada_en)
SELECT id, 'v3 hito 3', 'PUBLICADA', now() FROM organizacion WHERE codigo = 'RENASER';

INSERT INTO peso_etapa (version_pesos_id, etapa_codigo, peso)
SELECT vp.id, e.codigo, e.peso::numeric
FROM version_pesos vp,
     -- 40/(40+30)*100 = 57.14, 30/(40+30)*100 = 42.86
     (VALUES ('PERFIL_INTEGRAL', 57.14), ('PRUEBA_PUESTO', 42.86)) AS e(codigo, peso)
WHERE vp.etiqueta = 'v3 hito 3';

INSERT INTO peso_componente_perfil (version_pesos_id, componente, peso)
SELECT vp.id, c.componente, c.peso::numeric
FROM version_pesos vp,
     (VALUES ('CV', 17.14), ('PSICOMETRICO', 0), ('EVALUACION', 40)) AS c(componente, peso)
WHERE vp.etiqueta = 'v3 hito 3';

-- Las vacantes que ya estén publicadas migran a la v3: sin esto, calcular su decisión
-- final se toparía con una versión que solo sabe repartir 70 de 100.
UPDATE vacante v
SET version_pesos_id = vp.id
FROM version_pesos vp
WHERE vp.etiqueta = 'v3 hito 3'
  AND v.organizacion_id = vp.organizacion_id
  AND v.version_pesos_id != vp.id;

-- ============================================================================
-- 4b · Umbrales del semáforo de decisión
-- ============================================================================
-- ⚠️ Igual que los umbrales de grupo de prioridad del hito 2: ningún documento dice
-- dónde está la frontera. RF-117 describe el semáforo por barreras y evidencia, no por
-- una nota de corte, así que estos dos son una interpretación nuestra -razonable pero
-- nuestra- para que la propuesta tenga con qué arrancar. Van como parámetro editable
-- para que Renaser los corrija sin tocar código.
INSERT INTO parametro (organizacion_id, codigo, valor, tipo, descripcion)
SELECT o.id, p.codigo, p.valor, p.tipo, p.descripcion
FROM organizacion o,
     (VALUES
        ('umbral_decision_verde', '75', 'ENTERO',
         'Puntuación Global a partir de la cual la propuesta de decisión es verde'),
        ('umbral_decision_rojo', '50', 'ENTERO',
         'Puntuación Global por debajo de la cual la propuesta es roja en vez de ámbar')
     ) AS p(codigo, valor, tipo, descripcion)
WHERE o.codigo = 'RENASER';

-- ============================================================================
-- 5 · Permisos nuevos
-- ============================================================================
-- docs/04-ROLES-Y-PERMISOS.md: la decisión final NO es de Talento -la toma quien se
-- hace cargo del resultado-, así que decidir_contratacion se asigna distinto a todo lo
-- demás de este bloque.
INSERT INTO permiso (codigo, etiqueta, grupo, orden) VALUES
    ('editar_plantillas_prueba',  'Crear o editar plantillas de prueba',             'CONFIGURACION', 11),
    ('elegir_plantilla_prueba',   'Elegir qué prueba se aplica a una vacante',       'EVALUACION',    10),
    ('definir_barreras_criticas', 'Definir las barreras críticas de una vacante',    'VACANTES',      8),
    ('ver_semaforo_decision',     'Ver el resultado del semáforo de decisión',       'EVALUACION',    11),
    ('decidir_contratacion',      'Tomar la decisión final de contratación',         'EVALUACION',    12),
    ('pedir_evidencia_adicional', 'Pedir evidencia adicional cuando sale ámbar',     'EVALUACION',    13),
    ('pasar_a_reserva',           'Pasar a un candidato al Radar de Talento',        'EVALUACION',    14),
    ('cambiar_decision',          'Cambiar una decisión ya tomada',                  'EVALUACION',    15);

INSERT INTO rol_permiso (rol_id, permiso_id, alcance)
SELECT r.id, p.id, x.alcance
FROM (VALUES
    -- Talento: prepara la prueba y ve el semáforo, pero no decide
    ('TALENTO', 'editar_plantillas_prueba',  'TODO'),
    ('TALENTO', 'elegir_plantilla_prueba',   'TODO'),
    ('TALENTO', 'definir_barreras_criticas', 'TODO'),
    ('TALENTO', 'ver_semaforo_decision',     'TODO'),
    ('TALENTO', 'pedir_evidencia_adicional', 'TODO'),
    ('TALENTO', 'pasar_a_reserva',           'TODO'),
    ('TALENTO', 'cambiar_decision',          'TODO'),
    -- Responsable del área: gana la decisión final de sus vacantes (RF-119), que en
    -- el hito 1 no tenía ningún permiso de escritura sobre la postulación
    ('RESPONSABLE_AREA', 'elegir_plantilla_prueba',    'SUS_VACANTES'),
    ('RESPONSABLE_AREA', 'definir_barreras_criticas',  'SUS_VACANTES'),
    ('RESPONSABLE_AREA', 'ver_semaforo_decision',      'SUS_VACANTES'),
    ('RESPONSABLE_AREA', 'decidir_contratacion',       'SUS_VACANTES'),
    ('RESPONSABLE_AREA', 'pedir_evidencia_adicional',  'SUS_VACANTES'),
    ('RESPONSABLE_AREA', 'pasar_a_reserva',            'SUS_VACANTES'),
    ('RESPONSABLE_AREA', 'cambiar_decision',           'SUS_VACANTES'),
    -- Dirección: todo, incluida la publicación de plantillas
    ('DIRECCION', 'editar_plantillas_prueba',  'TODO'),
    ('DIRECCION', 'elegir_plantilla_prueba',   'TODO'),
    ('DIRECCION', 'definir_barreras_criticas', 'TODO'),
    ('DIRECCION', 'ver_semaforo_decision',     'TODO'),
    ('DIRECCION', 'decidir_contratacion',      'TODO'),
    ('DIRECCION', 'pedir_evidencia_adicional', 'TODO'),
    ('DIRECCION', 'pasar_a_reserva',           'TODO'),
    ('DIRECCION', 'cambiar_decision',          'TODO')
) AS x(rol_codigo, permiso_codigo, alcance)
JOIN rol r ON r.codigo = x.rol_codigo
JOIN permiso p ON p.codigo = x.permiso_codigo
WHERE r.organizacion_id = (SELECT id FROM organizacion WHERE codigo = 'RENASER');
