-- Etapas 4 y 5: Simulación de trabajo y Validación práctica.
-- Ver docs/01-REQUISITOS-FUNCIONALES.md §7 (RF-91 a RF-104) y §8 (RF-105 a RF-112),
-- docs/07-DICCIONARIO-DE-DATOS.md §15 y §16, docs/03-ESTADOS-POSTULACION.md.
--
-- Estas dos etapas estaban fuera del MVP por razones no técnicas: la simulación necesita un
-- facilitador y gente coordinada, la validación una figura contractual que Renaser no había
-- definido. Ambas se destrabaron: el facilitador se resuelve con los roles que ya existen
-- (configurable por parámetro, ver §6) y la figura contractual entra con un valor provisional.
--
-- Con esto el recorrido queda completo: desaparece el guardia de ServicioPostulacionesPanelImpl
-- que obligaba a saltar a mano de la prueba a la decisión.

-- ============================================================================
-- 1 · Las sesiones de simulación
-- ============================================================================

CREATE TABLE sesion_simulacion (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id       bigint NOT NULL REFERENCES organizacion(id),
    fecha_hora            timestamptz NOT NULL,
    duracion_minutos      integer NOT NULL,
    modalidad             text NOT NULL CHECK (modalidad IN ('GRUPAL', 'INDIVIDUAL')),
    lugar                 text,
    enlace                text,
    cupo                  integer NOT NULL CHECK (cupo > 0),
    estado                text NOT NULL CHECK (estado IN ('PUBLICADA', 'LLENA', 'CANCELADA', 'TERMINADA')),
    enunciado             text,
    creada_por_usuario_id bigint NOT NULL REFERENCES usuario(id),
    creado_en             timestamptz NOT NULL DEFAULT now()
);

-- Para qué vacantes sirve una sesión: una, varias o todas. El candidato solo ve las suyas.
CREATE TABLE sesion_vacante (
    sesion_simulacion_id bigint NOT NULL REFERENCES sesion_simulacion(id),
    vacante_id           bigint NOT NULL REFERENCES vacante(id),
    creado_en            timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (sesion_simulacion_id, vacante_id)
);

-- RF-91 dice que una sesión se crea con "responsables", en plural. sesion_simulacion solo
-- guarda quién la creó, que no es lo mismo que quién la conduce. Sin esta tabla no se puede
-- saber quién facilitó cada sesión, y "quién puede facilitar" queda en el parámetro
-- roles_facilitador_simulacion (§6), editable desde el panel sin tocar código.
CREATE TABLE sesion_responsable (
    sesion_simulacion_id bigint NOT NULL REFERENCES sesion_simulacion(id),
    usuario_id           bigint NOT NULL REFERENCES usuario(id),
    creado_en            timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (sesion_simulacion_id, usuario_id)
);

-- El reparto de minutos es por sesión, no un catálogo global: RF-96 dice que es configurable.
-- Se copian de un valor por defecto al crear la sesión.
CREATE TABLE tramo_simulacion (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sesion_simulacion_id bigint NOT NULL REFERENCES sesion_simulacion(id),
    codigo               text NOT NULL CHECK (codigo IN
                             ('CONTEXTO', 'PREGUNTAS', 'EJECUCION', 'CAMBIO', 'ENTREGA', 'CONVERSACION')),
    nombre               text NOT NULL,
    minuto_inicio        integer NOT NULL,
    minuto_fin           integer NOT NULL,
    creado_en            timestamptz NOT NULL DEFAULT now(),
    UNIQUE (sesion_simulacion_id, codigo),
    CHECK (minuto_inicio < minuto_fin)
);

-- Qué debería preguntar un candidato fuerte. Declararlo de antemano es lo que permite
-- calificar "no preguntó lo importante" sin que sea una opinión (RF-99).
CREATE TABLE informacion_critica (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sesion_simulacion_id bigint NOT NULL REFERENCES sesion_simulacion(id),
    tipo                 text NOT NULL CHECK (tipo IN ('DEBE_PREGUNTAR', 'OPCIONAL', 'DEBE_DESCUBRIR')),
    texto                text NOT NULL,
    orden                integer NOT NULL,
    creado_en            timestamptz NOT NULL DEFAULT now()
);

-- ============================================================================
-- 2 · La inscripción del candidato y lo que ocurre en la sesión
-- ============================================================================

-- es_vigente permite guardar el historial: si su sesión se cancela, esa inscripción se queda
-- como estaba y se crea otra. El único parcial garantiza una sola inscripción activa.
-- asistio es tri-estado a propósito: vacío significa "nadie lo ha marcado todavía", que es
-- distinto de "no asistió".
CREATE TABLE inscripcion_sesion (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sesion_simulacion_id   bigint NOT NULL REFERENCES sesion_simulacion(id),
    postulacion_id         bigint NOT NULL REFERENCES postulacion(id),
    inscrita_en            timestamptz NOT NULL DEFAULT now(),
    asistio                boolean,
    marcada_por_usuario_id bigint REFERENCES usuario(id),
    es_vigente             boolean NOT NULL DEFAULT true,
    creado_en              timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX inscripcion_sesion_vigente_unica_idx
    ON inscripcion_sesion (postulacion_id) WHERE es_vigente;

-- Los momentos OBSERVABLES, y solo esos.
-- ⚠️ RF-98: antes había una marca para "cuándo detectó el bloqueo" y el cliente la prohíbe
-- expresamente. No se registra lo que alguien pensó, solo lo que hizo. Por eso quedan
-- APARECE_CAMBIO y ABRE_CAMBIO, que son dos actos, y no "se dio cuenta del cambio".
CREATE TABLE marca_tiempo_simulacion (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inscripcion_sesion_id  bigint NOT NULL REFERENCES inscripcion_sesion(id),
    evento                 text NOT NULL CHECK (evento IN
                               ('INICIO', 'PRIMERA_PREGUNTA', 'INICIO_TRABAJO', 'PRIMERA_EVIDENCIA',
                                'APARECE_CAMBIO', 'ABRE_CAMBIO', 'PRIMERA_REACCION_CAMBIO',
                                'COMUNICA_RIESGO', 'ENTREGA', 'AUTOCRITICA')),
    ocurrida_en            timestamptz NOT NULL,
    creado_en              timestamptz NOT NULL DEFAULT now(),
    UNIQUE (inscripcion_sesion_id, evento)
);

-- Las 3 a 5 preguntas de la conversación final. Las genera un agente que todavía no existe,
-- así que por ahora se registran a mano; cuando exista, rellena esta misma tabla.
-- riesgo_resuelto es lo que evita un módulo de entrevista aparte: con eso y la observación basta.
CREATE TABLE pregunta_generada (
    id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postulacion_id            bigint NOT NULL REFERENCES postulacion(id),
    texto                     text NOT NULL,
    alerta_id                 bigint REFERENCES alerta(id),
    ejecucion_ia_id           bigint REFERENCES ejecucion_ia(id),
    respuesta                 text,
    riesgo_resuelto           boolean,
    observacion               text,
    registrada_por_usuario_id bigint REFERENCES usuario(id),
    orden                     integer NOT NULL,
    creado_en                 timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX sesion_simulacion_org_estado_idx ON sesion_simulacion (organizacion_id, estado);
CREATE INDEX sesion_vacante_vacante_idx ON sesion_vacante (vacante_id);
CREATE INDEX inscripcion_sesion_sesion_idx ON inscripcion_sesion (sesion_simulacion_id);
CREATE INDEX marca_tiempo_inscripcion_idx ON marca_tiempo_simulacion (inscripcion_sesion_id);
CREATE INDEX pregunta_generada_postulacion_idx ON pregunta_generada (postulacion_id);
CREATE INDEX informacion_critica_sesion_idx ON informacion_critica (sesion_simulacion_id);
CREATE INDEX tramo_simulacion_sesion_idx ON tramo_simulacion (sesion_simulacion_id);

-- ============================================================================
-- 3 · La validación práctica
-- ============================================================================

-- El CHECK de tipo_vinculacion es la regla que impide que una aceptación digital sustituya
-- una obligación legal: no se puede poner a alguien a trabajar de verdad sin figura contractual.
-- La otra modalidad -simulación extendida, sin trabajo productivo- no la necesita y se puede
-- usar desde el primer día (RF-106).
--
-- fin_en se guarda como fecha concreta y no se calcula, para que el barrido que cierra
-- periodos vencidos sea una consulta directa sobre columna indexada.
CREATE TABLE validacion (
    id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postulacion_id            bigint NOT NULL REFERENCES postulacion(id),
    modalidad                 text NOT NULL CHECK (modalidad IN ('SIMULACION_EXTENDIDA', 'TRABAJO_REAL')),
    tipo_vinculacion          text,
    dias                      integer NOT NULL,
    inicio_en                 timestamptz,
    fin_en                    timestamptz,
    estado                    text NOT NULL CHECK (estado IN ('POR_HABILITAR', 'EN_CURSO', 'TERMINADA')),
    habilitada_por_usuario_id bigint REFERENCES usuario(id),
    responsable_usuario_id    bigint REFERENCES usuario(id),
    creado_en                 timestamptz NOT NULL DEFAULT now(),
    UNIQUE (postulacion_id),
    CHECK (modalidad <> 'TRABAJO_REAL' OR (tipo_vinculacion IS NOT NULL AND btrim(tipo_vinculacion) <> ''))
);

CREATE INDEX validacion_fin_idx ON validacion (fin_en) WHERE estado = 'EN_CURSO';

-- ============================================================================
-- 4 · Los criterios de las dos etapas
-- ============================================================================
-- Son criterios GLOBALES -version_plantilla_prueba_id vacío-, igual que los ocho del
-- currículum del hito 2: valen para cualquier vacante. Los de la prueba del puesto, en
-- cambio, cuelgan de su versión de plantilla porque cada prueba tiene la suya.

-- RF-100: los diez de la simulación, que suman 100
INSERT INTO criterio (codigo, nombre, descripcion, etapa_codigo, metodo_verificacion, orden) VALUES
    ('SIM_COMPRENSION',   'Comprensión del resultado',  'Entendió qué había que lograr, no solo qué había que hacer', 'SIMULACION', 'PERSONA', 1),
    ('SIM_PREGUNTAS',     'Calidad de las preguntas',   'Preguntó lo que un candidato fuerte preguntaría',            'SIMULACION', 'PERSONA', 2),
    ('SIM_ARRANQUE',      'Velocidad de arranque',      'Cuánto tardó en empezar a producir algo',                    'SIMULACION', 'SISTEMA', 3),
    ('SIM_PRIORIZACION',  'Priorización',               'Atacó primero lo que más movía el resultado',                'SIMULACION', 'PERSONA', 4),
    ('SIM_EJECUCION',     'Ejecución',                  'Lo que produjo durante la sesión',                           'SIMULACION', 'PERSONA', 5),
    ('SIM_CALIDAD',       'Calidad',                    'Qué tan bien hecho está lo que entregó',                     'SIMULACION', 'PERSONA', 6),
    ('SIM_AUTONOMIA',     'Autonomía',                  'Avanzó sin que lo empujaran',                                'SIMULACION', 'PERSONA', 7),
    ('SIM_COMUNICACION',  'Comunicación preventiva',    'Avisó del riesgo antes de que fuera un problema',            'SIMULACION', 'PERSONA', 8),
    ('SIM_RECURSOS',      'Uso de recursos e IA',       'Aprovechó las herramientas y verificó lo que produjeron',    'SIMULACION', 'PERSONA', 9),
    ('SIM_APRENDIZAJE',   'Evidencia y aprendizaje',    'Lo que dice se puede comprobar, y sacó algo en limpio',      'SIMULACION', 'PERSONA', 10);

-- RF-109: las nueve métricas de la validación, que suman 100
INSERT INTO criterio (codigo, nombre, descripcion, etapa_codigo, metodo_verificacion, orden) VALUES
    ('VAL_RESULTADO',     'Resultado logrado',            'Lo que se esperaba del periodo, conseguido',        'VALIDACION', 'PERSONA', 1),
    ('VAL_CALIDAD',       'Calidad al primer intento',    'Cuánto hubo que rehacer',                           'VALIDACION', 'PERSONA', 2),
    ('VAL_VELOCIDAD',     'Velocidad',                    'Entregó en el tiempo esperado',                     'VALIDACION', 'SISTEMA', 3),
    ('VAL_CONFIABILIDAD', 'Confiabilidad',                'Se puede contar con que lo que dice que hará, ocurre', 'VALIDACION', 'PERSONA', 4),
    ('VAL_AUTONOMIA',     'Autonomía',                    'Cuánto seguimiento necesitó',                       'VALIDACION', 'PERSONA', 5),
    ('VAL_COMUNICACION',  'Comunicación preventiva',      'Avisó a tiempo de lo que iba a fallar',             'VALIDACION', 'PERSONA', 6),
    ('VAL_APRENDIZAJE',   'Aprendizaje entre iteraciones','Mejoró de una entrega a la siguiente',              'VALIDACION', 'PERSONA', 7),
    ('VAL_SERVICIO',      'Servicio',                     'Cómo trató a quien recibía su trabajo',             'VALIDACION', 'PERSONA', 8),
    ('VAL_SISTEMA',       'Aporte al sistema',            'Dejó algo que sirve más allá de sus tareas',        'VALIDACION', 'PERSONA', 9);

-- ============================================================================
-- 5 · Una versión de pesos con las cuatro etapas
-- ============================================================================
-- La v3 del hito 3 repartía entre dos etapas los 30 puntos de simulación y validación, porque
-- esas etapas no existían y había que puntuar sobre 100 igual. Ahora que existen, ese apaño
-- sobra: la v4 devuelve el reparto original 40/30/15/15 (RF: peso_etapa).
-- La v3 no se toca -una versión publicada es inmutable-, pero las vacantes migran a la v4.
INSERT INTO version_pesos (organizacion_id, etiqueta, estado, publicada_en)
SELECT id, 'v4 embudo completo', 'PUBLICADA', now() FROM organizacion WHERE codigo = 'RENASER';

INSERT INTO peso_etapa (version_pesos_id, etapa_codigo, peso)
SELECT vp.id, e.codigo, e.peso::numeric
FROM version_pesos vp,
     (VALUES ('PERFIL_INTEGRAL', 40), ('PRUEBA_PUESTO', 30), ('SIMULACION', 15), ('VALIDACION', 15))
         AS e(codigo, peso)
WHERE vp.etiqueta = 'v4 embudo completo';

-- El módulo psicométrico sigue sin existir, así que su 5% se reparte entre los otros dos
-- componentes del Perfil Integral, igual que en la v2 (RF-37).
INSERT INTO peso_componente_perfil (version_pesos_id, componente, peso)
SELECT vp.id, c.componente, c.peso::numeric
FROM version_pesos vp,
     (VALUES ('CV', 12), ('PSICOMETRICO', 0), ('EVALUACION', 28)) AS c(componente, peso)
WHERE vp.etiqueta = 'v4 embudo completo';

-- Los pesos de criterio de la v4: los ocho del currículum (RF-43, por nivel) más los diez de
-- simulación y las nueve de validación (iguales para los tres niveles).
INSERT INTO peso_criterio (version_pesos_id, nivel_puesto_codigo, criterio_id, peso)
SELECT vp.id, x.nivel, c.id, x.peso::numeric
FROM version_pesos vp
JOIN (VALUES
        ('CV_RESULTADOS',  'DIRECCION', 25), ('CV_RESULTADOS',  'SUPERVISION', 20), ('CV_RESULTADOS',  'EJECUCION', 20),
        ('CV_COMPLEJIDAD', 'DIRECCION', 15), ('CV_COMPLEJIDAD', 'SUPERVISION', 10), ('CV_COMPLEJIDAD', 'EJECUCION',  5),
        ('CV_SISTEMAS',    'DIRECCION', 15), ('CV_SISTEMAS',    'SUPERVISION', 15), ('CV_SISTEMAS',    'EJECUCION', 10),
        ('CV_PERSONAS',    'DIRECCION', 15), ('CV_PERSONAS',    'SUPERVISION', 15), ('CV_PERSONAS',    'EJECUCION',  0),
        ('CV_APRENDIZAJE', 'DIRECCION', 10), ('CV_APRENDIZAJE', 'SUPERVISION', 10), ('CV_APRENDIZAJE', 'EJECUCION', 15),
        ('CV_INICIATIVA',  'DIRECCION',  5), ('CV_INICIATIVA',  'SUPERVISION', 10), ('CV_INICIATIVA',  'EJECUCION', 10),
        ('CV_HABILIDADES', 'DIRECCION',  5), ('CV_HABILIDADES', 'SUPERVISION', 10), ('CV_HABILIDADES', 'EJECUCION', 25),
        ('CV_EVIDENCIA',   'DIRECCION', 10), ('CV_EVIDENCIA',   'SUPERVISION', 10), ('CV_EVIDENCIA',   'EJECUCION', 15)
     ) AS x(codigo, nivel, peso) ON true
JOIN criterio c ON c.codigo = x.codigo AND c.version_plantilla_prueba_id IS NULL
WHERE vp.etiqueta = 'v4 embudo completo';

INSERT INTO peso_criterio (version_pesos_id, nivel_puesto_codigo, criterio_id, peso)
SELECT vp.id, n.codigo, c.id, x.peso::numeric
FROM version_pesos vp
JOIN (VALUES
        ('SIM_COMPRENSION', 10), ('SIM_PREGUNTAS', 10), ('SIM_ARRANQUE', 10), ('SIM_PRIORIZACION', 10),
        ('SIM_EJECUCION', 15), ('SIM_CALIDAD', 15), ('SIM_AUTONOMIA', 10), ('SIM_COMUNICACION', 10),
        ('SIM_RECURSOS', 5), ('SIM_APRENDIZAJE', 5),
        ('VAL_RESULTADO', 25), ('VAL_CALIDAD', 15), ('VAL_VELOCIDAD', 10), ('VAL_CONFIABILIDAD', 10),
        ('VAL_AUTONOMIA', 10), ('VAL_COMUNICACION', 10), ('VAL_APRENDIZAJE', 10), ('VAL_SERVICIO', 5),
        ('VAL_SISTEMA', 5)
     ) AS x(codigo, peso) ON true
JOIN criterio c ON c.codigo = x.codigo AND c.version_plantilla_prueba_id IS NULL
JOIN nivel_puesto n ON true
WHERE vp.etiqueta = 'v4 embudo completo';

-- Los pesos de dimensión de la v4: se copian de la v2 tal cual.
--
-- La v4 cambia cómo se reparte el puntaje ENTRE etapas, no lo que vale cada dimensión del
-- banco dentro del Perfil de Talento. Copiar es lo correcto; inventar números nuevos, no.
--
-- Sin esto la versión activa se queda sin `peso_dimension` y se repite el hueco de la V15:
-- el panel de pesos muestra la rejilla de dimensiones vacía, y `validarSumas` da por buena
-- una versión que no tiene ninguna fila que sumar. Hoy no altera la nota que calcula la IA
-- -ese camino no lee esta tabla-, pero deja publicada una versión incompleta.
INSERT INTO peso_dimension (version_pesos_id, nivel_puesto_codigo, dimension_codigo, peso)
SELECT destino.id, pd.nivel_puesto_codigo, pd.dimension_codigo, pd.peso
FROM peso_dimension pd
JOIN version_pesos origen  ON origen.id = pd.version_pesos_id AND origen.etiqueta = 'v2 hito 2'
JOIN version_pesos destino ON destino.organizacion_id = origen.organizacion_id
                          AND destino.etiqueta = 'v4 embudo completo'
WHERE NOT EXISTS (
    SELECT 1 FROM peso_dimension ya
    WHERE ya.version_pesos_id = destino.id
      AND ya.nivel_puesto_codigo = pd.nivel_puesto_codigo
      AND ya.dimension_codigo = pd.dimension_codigo
);

-- Las vacantes migran a la v4: si se quedaran en la v3 no podrían puntuar las dos etapas nuevas.
UPDATE vacante v
SET version_pesos_id = vp.id
FROM version_pesos vp
WHERE vp.etiqueta = 'v4 embudo completo'
  AND v.organizacion_id = vp.organizacion_id
  AND v.version_pesos_id <> vp.id;

-- ============================================================================
-- 6 · Parámetros: quién facilita y quién completa métricas
-- ============================================================================
-- Esto es lo que hace que "el facilitador" no necesite un rol nuevo. La documentación ya
-- reparte esas acciones entre los roles que existen, y para la validación dice literalmente
-- que "quién completa es configurable: puede ser solo el responsable del área, solo Talento, o
-- ambos. Arranca con ambos habilitados".
--
-- Cambiarlo después es PUT /panel/parametros/{codigo}, sin tocar código ni desplegar.
INSERT INTO parametro (organizacion_id, codigo, valor, tipo, descripcion)
SELECT o.id, p.codigo, p.valor, p.tipo, p.descripcion
FROM organizacion o,
     (VALUES
        ('roles_facilitador_simulacion', 'TALENTO,DIRECCION', 'LISTA',
         'Qué roles pueden conducir una sesión de simulación y marcar sus eventos'),
        ('roles_completan_metricas_validacion', 'TALENTO,RESPONSABLE_AREA', 'LISTA',
         'Qué roles pueden completar las métricas de la validación práctica'),
        ('dias_validacion_por_defecto', '7', 'ENTERO',
         'Cuántos días dura un periodo de validación si nadie dice otra cosa')
     ) AS p(codigo, valor, tipo, descripcion)
WHERE o.codigo = 'RENASER';

-- ============================================================================
-- 7 · El correo que faltaba
-- ============================================================================
-- RF-95: "Si se cancela, a los inscritos se les avisa y vuelven a elegir". Sin esta plantilla
-- el aviso no se puede mandar.
INSERT INTO plantilla_correo (organizacion_id, codigo, version, asunto, cuerpo, es_activa)
SELECT o.id, p.codigo, 1, p.asunto, p.cuerpo, true
FROM organizacion o,
     (VALUES
        ('SESION_CANCELADA', 'Se canceló tu sesión de {{vacante}}',
         'Hola {{nombre}}:' || E'\n\n' || 'La sesión que habías elegido para «{{vacante}}» se canceló. Entra a tu panel para elegir otra fecha; si todavía no hay ninguna disponible, te avisaremos en cuanto la haya.' || E'\n\n' || 'Equipo de Talento · Renaser'),
        ('SESION_DISPONIBLE', 'Ya puedes elegir fecha para {{vacante}}',
         'Hola {{nombre}}:' || E'\n\n' || 'Ya hay fechas disponibles para la sesión de trabajo de «{{vacante}}». Entra a tu panel y elige la que mejor te venga.' || E'\n\n' || 'Equipo de Talento · Renaser')
     ) AS p(codigo, asunto, cuerpo)
WHERE o.codigo = 'RENASER';

-- ============================================================================
-- 8 · Permisos
-- ============================================================================
-- Copiados de las matrices de docs/04-ROLES-Y-PERMISOS.md tal cual, incluidos los dos matices
-- que no son obvios: "marcar quién asistió" es la única acción de simulación donde el
-- responsable de área tiene alcance pleno, y "crear sesiones" y "decidir qué hacer con un
-- ausente" están cerradas para él.
INSERT INTO permiso (codigo, etiqueta, grupo, orden) VALUES
    ('crear_sesiones_simulacion',   'Crear sesiones de simulación con fecha y cupo',   'SESIONES',   1),
    ('definir_informacion_critica', 'Definir la matriz de información crítica',        'SESIONES',   2),
    ('marcar_eventos_simulacion',   'Marcar los eventos observables de una sesión',    'SESIONES',   3),
    ('marcar_asistencia',           'Marcar quién asistió a una sesión',               'SESIONES',   4),
    ('decidir_sobre_ausente',       'Decidir qué hacer con quien faltó a su sesión',   'SESIONES',   5),
    ('calificar_simulacion',        'Calificar la simulación de un candidato',         'SESIONES',   6),
    ('hacer_conversacion_final',    'Registrar la conversación final',                 'SESIONES',   7),
    ('elegir_sesion_simulacion',    'Elegir la fecha de su sesión',                    'SESIONES',   8),
    ('habilitar_validacion',        'Registrar la figura contractual y habilitar',     'VALIDACION', 1),
    ('iniciar_validacion',          'Iniciar el periodo de validación',                'VALIDACION', 2),
    ('completar_metricas_validacion','Completar las métricas que no se alimentan solas','VALIDACION', 3),
    ('cerrar_validacion',           'Cerrar el periodo de validación',                 'VALIDACION', 4);

INSERT INTO rol_permiso (rol_id, permiso_id, alcance)
SELECT r.id, p.id, x.alcance
FROM (VALUES
    -- El candidato solo elige su fecha
    ('CANDIDATO', 'elegir_sesion_simulacion', 'PROPIO'),
    -- Talento opera la simulación entera
    ('TALENTO', 'crear_sesiones_simulacion',    'TODO'),
    ('TALENTO', 'definir_informacion_critica',  'TODO'),
    ('TALENTO', 'marcar_eventos_simulacion',    'TODO'),
    ('TALENTO', 'marcar_asistencia',            'TODO'),
    ('TALENTO', 'decidir_sobre_ausente',        'TODO'),
    ('TALENTO', 'calificar_simulacion',         'TODO'),
    ('TALENTO', 'hacer_conversacion_final',     'TODO'),
    ('TALENTO', 'habilitar_validacion',         'TODO'),
    ('TALENTO', 'iniciar_validacion',           'TODO'),
    ('TALENTO', 'completar_metricas_validacion','TODO'),
    ('TALENTO', 'cerrar_validacion',            'TODO'),
    -- Responsable de área: solo lo suyo, y NO crea sesiones ni decide sobre ausentes.
    -- Marcar asistencia es la única con alcance pleno: puede estar en la sala sin ser
    -- responsable de esa vacante.
    ('RESPONSABLE_AREA', 'definir_informacion_critica',  'SUS_VACANTES'),
    ('RESPONSABLE_AREA', 'marcar_eventos_simulacion',    'SUS_VACANTES'),
    ('RESPONSABLE_AREA', 'marcar_asistencia',            'TODO'),
    ('RESPONSABLE_AREA', 'calificar_simulacion',         'SUS_VACANTES'),
    ('RESPONSABLE_AREA', 'hacer_conversacion_final',     'SUS_VACANTES'),
    ('RESPONSABLE_AREA', 'completar_metricas_validacion','SUS_VACANTES'),
    ('RESPONSABLE_AREA', 'cerrar_validacion',            'SUS_VACANTES'),
    -- Dirección: todo
    ('DIRECCION', 'crear_sesiones_simulacion',    'TODO'),
    ('DIRECCION', 'definir_informacion_critica',  'TODO'),
    ('DIRECCION', 'marcar_eventos_simulacion',    'TODO'),
    ('DIRECCION', 'marcar_asistencia',            'TODO'),
    ('DIRECCION', 'decidir_sobre_ausente',        'TODO'),
    ('DIRECCION', 'calificar_simulacion',         'TODO'),
    ('DIRECCION', 'hacer_conversacion_final',     'TODO'),
    ('DIRECCION', 'habilitar_validacion',         'TODO'),
    ('DIRECCION', 'iniciar_validacion',           'TODO'),
    ('DIRECCION', 'completar_metricas_validacion','TODO'),
    ('DIRECCION', 'cerrar_validacion',            'TODO')
) AS x(rol_codigo, permiso_codigo, alcance)
JOIN rol r ON r.codigo = x.rol_codigo
JOIN permiso p ON p.codigo = x.permiso_codigo
WHERE r.organizacion_id = (SELECT id FROM organizacion WHERE codigo = 'RENASER');
