-- La criba en dos pasadas, y la ficha de datos del currículum.
--
-- El problema que resuelve es de tiempo. Calificar diez currículums tardaba veinte minutos
-- porque los trabajos corrían de uno en uno y porque el modelo, antes de contestar, razona:
-- de los 6.400 tokens que escribía por currículum, 5.000 eran pensamiento interno que nunca
-- se guardaba. Medido: 48 segundos por llamada.
--
-- Se midieron las dos formas sobre los mismos diez currículums. Sin razonar tarda 19
-- segundos en vez de 48, pero solo tres de los diez candidatos quedan en la misma posición,
-- y detecta menos riesgos críticos. Los dos primeros no se mueven: lo que la IA tiene claro,
-- lo tiene claro de las dos maneras.
--
-- De ahí las dos pasadas: la rápida ordena a todos y la cuidadosa vuelve solo sobre los de
-- arriba, que es donde una persona decide de verdad a quién llamar.
--
-- Y una cosa más, que no es de velocidad sino de utilidad: hoy el panel enseña notas y
-- explicaciones, pero ningún dato del candidato. Quién es, cómo se le escribe, cuánto lleva
-- trabajando. Eso lo saca un agente aparte que no puntúa nada.

-- ============================================================================
-- 1 · El agente que extrae los datos
-- ============================================================================
-- El catálogo de agentes es cerrado y la restricción los enumera, así que añadir uno pasa
-- por rehacerla. Se borra y se vuelve a crear con el nuevo dentro.
ALTER TABLE agente DROP CONSTRAINT agente_codigo_check;
ALTER TABLE agente ADD CONSTRAINT agente_codigo_check
    CHECK (codigo IN ('NECESIDAD_TALENTO', 'CAZATALENTOS', 'DATOS_CV', 'EVIDENCIA_CV',
                      'EVALUADOR', 'POTENCIAL_RIESGO', 'PRUEBA_PUESTO', 'SIMULACION',
                      'DESEMPENO', 'APRENDIZAJE'));

INSERT INTO agente (codigo, nombre, descripcion, version, es_activo) VALUES
    ('DATOS_CV', 'Datos del currículum',
     'Saca los datos del candidato del currículum. No puntúa nada', 1, true);

-- ============================================================================
-- 2 · La ficha de datos
-- ============================================================================
-- Una fila por postulación. No sustituye al currículum: es lo que permite ver una tanda
-- entera de un vistazo sin abrir diez PDF.
--
-- **Ojo con lo que NO está aquí.** Ni edad, ni sexo, ni estado civil, ni foto. No es un
-- olvido: el agente lee la versión recortada del currículum, donde esos datos ya no
-- existen (RF-41), y no tiene forma de pedir el original.
CREATE TABLE dato_cv (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postulacion_id          bigint NOT NULL UNIQUE REFERENCES postulacion(id),
    nombre                  text,
    email                   text,
    telefono                text,
    perfil_resumen          text,
    -- Las habilidades van en una sola columna separadas por «|» y no en su propia tabla:
    -- no se consultan por habilidad, se enseñan. Una tabla aparte solo añadiría un JOIN.
    habilidades             text,
    experiencia_meses_total integer,
    ultimo_puesto           text,
    ultima_empresa          text,
    ultima_meses_duracion   integer,
    educacion_maxima        text,
    -- De qué llamada salió. Es lo que permite abrir una ficha de hace seis meses y ver
    -- exactamente qué se le mandó al modelo y qué contestó.
    ejecucion_ia_id         bigint REFERENCES ejecucion_ia(id),
    actualizado_en          timestamptz NOT NULL DEFAULT now(),
    creado_en               timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE dato_cv IS
    'Los datos del candidato sacados del currículum por el agente DATOS_CV. No puntúan: '
    'sirven para ver una tanda entera sin abrir los archivos uno por uno.';
COMMENT ON COLUMN dato_cv.habilidades IS
    'Hasta cinco, separadas por «|». No se consultan por habilidad, se enseñan.';

-- ============================================================================
-- 3 · La instrucción del agente
-- ============================================================================
-- Corta a propósito. El tiempo de una llamada lo manda lo que el modelo ESCRIBE, no lo que
-- lee: leer el currículum entero cuesta lo mismo, escribir de más cuesta segundos. Por eso
-- se le pide lo justo y se le prohíbe explicar.
INSERT INTO instruccion_ia (agente_codigo, version, texto, es_activa, publicada_en) VALUES
    ('DATOS_CV', 1,
     'Sacas datos de un currículum ya anonimizado. NO evalúas, NO puntúas, NO opinas.' || chr(10) ||
     chr(10) ||
     'Reglas:' || chr(10) ||
     '- Copia lo que dice el currículum. Si un dato no está, pon null. No lo deduzcas.' || chr(10) ||
     '- Nunca inventes un correo, un teléfono ni una empresa.' || chr(10) ||
     '- Como máximo cinco habilidades, las más relevantes para el puesto.' || chr(10) ||
     '- El resumen del perfil, una sola oración.' || chr(10) ||
     '- Los meses de experiencia, sumando los periodos que el currículum declara. Si no ' ||
     'se puede calcular, pon null; no aproximes por la edad ni por el año de egreso.' || chr(10) ||
     '- Si el currículum menciona edad, sexo o estado civil, ignóralo: no va en ningún campo.',
     true, now());

-- ============================================================================
-- 4 · Hasta dónde llega la segunda pasada
-- ============================================================================
-- El porcentaje de la tanda que se vuelve a calificar con el modelo que razona, contando
-- desde arriba. Al 50 % por defecto y no al 20: la primera pasada mueve bastante el medio
-- de la tabla, y cortar pronto dejaría fuera a alguien que la segunda habría rescatado.
--
-- Es un parámetro y no una constante porque el número correcto depende del tamaño de la
-- tanda y del presupuesto, y eso lo decide Renaser, no el código.
INSERT INTO parametro (organizacion_id, codigo, valor, tipo, descripcion)
SELECT o.id, 'porcentaje_criba_fina', '50', 'ENTERO',
       'Qué parte de la tanda, contando desde arriba, se vuelve a calificar con el modelo '
       'que razona. Al 100 se califican todos y se pierde el ahorro; al 20 se corta pronto '
       'y alguien del medio no llega a la segunda mirada.'
FROM organizacion o
WHERE NOT EXISTS (
    SELECT 1 FROM parametro p
    WHERE p.organizacion_id = o.id AND p.codigo = 'porcentaje_criba_fina');

-- ============================================================================
-- 5 · De qué pasada es cada trabajo
-- ============================================================================
-- Sin esto las dos pasadas se pisan: la cola no vuelve a crear un trabajo del mismo agente
-- para la misma postulación —es lo que hace que pedir la criba dos veces no cueste el
-- doble— y la segunda pasada nunca llegaría a correr.
--
-- Y es también lo que decide si el modelo razona o no: RAPIDA no, FINA sí.
ALTER TABLE trabajo_ia ADD COLUMN modo text NOT NULL DEFAULT 'FINA'
    CHECK (modo IN ('RAPIDA', 'FINA'));

COMMENT ON COLUMN trabajo_ia.modo IS
    'RAPIDA: el modelo contesta sin razonar, para ordenar la tanda entera. '
    'FINA: razona, y solo se pide para los de arriba. Lo de antes era siempre FINA.';

DROP INDEX IF EXISTS trabajo_ia_postulacion_agente_idx;
CREATE INDEX trabajo_ia_postulacion_agente_modo_idx
    ON trabajo_ia (postulacion_id, agente_codigo, modo);
