-- Personas, cuentas, roles y permisos. Ver docs/07-DICCIONARIO-DE-DATOS.md §1 y §2.
-- Regla general del diccionario: ninguna FK borra en cascada — nada se borra en este sistema.

-- Renaser, y mañana cada cliente de consultoría. Toda entidad de negocio cuelga de aquí.
CREATE TABLE organizacion (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo     text NOT NULL UNIQUE,
    nombre     text NOT NULL,
    es_activa  boolean NOT NULL DEFAULT true,
    creado_en  timestamptz NOT NULL DEFAULT now()
);

-- Quién es alguien: vale para el equipo y para quien postula. Las columnas de identidad
-- admiten vacío porque el borrado de datos las vacía (anonimización, no DELETE).
CREATE TABLE persona (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           text,
    apellidos        text,
    telefono         text,
    documento        text,
    fecha_nacimiento date,
    anonimizado_en   timestamptz,
    creado_en        timestamptz NOT NULL DEFAULT now()
);

-- El departamento que contrata.
CREATE TABLE area (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id bigint NOT NULL REFERENCES organizacion(id),
    nombre          text NOT NULL,
    es_activa       boolean NOT NULL DEFAULT true,
    creado_en       timestamptz NOT NULL DEFAULT now(),
    UNIQUE (organizacion_id, nombre)
);

-- Cómo entra alguien al sistema. Candidatos: contraseña propia. Equipo: id de RENASER OS
-- (texto suelto, sin FK: son dos servicios separados). Nunca las dos cosas a la vez.
CREATE TABLE usuario (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id       bigint NOT NULL REFERENCES organizacion(id),
    persona_id            bigint NOT NULL REFERENCES persona(id),
    correo                text,
    contrasena_hash       text,
    usuario_renaser_os_id text,
    area_id               bigint REFERENCES area(id),
    es_activo             boolean NOT NULL DEFAULT true,
    ultimo_acceso_en      timestamptz,
    creado_en             timestamptz NOT NULL DEFAULT now(),
    UNIQUE (persona_id, organizacion_id),
    CONSTRAINT usuario_una_sola_identidad
        CHECK (contrasena_hash IS NULL OR usuario_renaser_os_id IS NULL)
);

-- El correo es único por organización, sin distinguir mayúsculas.
CREATE UNIQUE INDEX usuario_correo_unico_por_org ON usuario (organizacion_id, lower(correo));

-- Un nombre y una lista de permisos. Los cinco iniciales son de sistema y no se borran.
CREATE TABLE rol (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id bigint NOT NULL REFERENCES organizacion(id),
    codigo          text NOT NULL,
    nombre          text NOT NULL,
    descripcion     text,
    es_sistema      boolean NOT NULL DEFAULT false,
    creado_en       timestamptz NOT NULL DEFAULT now(),
    UNIQUE (organizacion_id, codigo)
);

-- Una acción suelta que se concede o no. Global: los permisos son los mismos para todas
-- las organizaciones y el catálogo solo crece con una migración.
CREATE TABLE permiso (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo    text NOT NULL UNIQUE,
    etiqueta  text NOT NULL,
    grupo     text NOT NULL,
    orden     integer NOT NULL,
    creado_en timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE usuario_rol (
    usuario_id              bigint NOT NULL REFERENCES usuario(id),
    rol_id                  bigint NOT NULL REFERENCES rol(id),
    asignado_por_usuario_id bigint REFERENCES usuario(id),
    creado_en               timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (usuario_id, rol_id)
);

-- El alcance va aquí y no en el permiso: el mismo permiso puede ser «todo» para Talento
-- y «solo lo suyo» para el responsable del área.
CREATE TABLE rol_permiso (
    rol_id     bigint NOT NULL REFERENCES rol(id),
    permiso_id bigint NOT NULL REFERENCES permiso(id),
    alcance    text NOT NULL CHECK (alcance IN ('PROPIO', 'SUS_VACANTES', 'TODO')),
    creado_en  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (rol_id, permiso_id)
);

-- FKs consultadas en joins que ningún único cubre (PostgreSQL no indexa FKs solo)
CREATE INDEX usuario_rol_rol_idx ON usuario_rol (rol_id);
CREATE INDEX rol_permiso_permiso_idx ON rol_permiso (permiso_id);
