-- Consentimiento versionado y borrado de datos. Ver docs/07-DICCIONARIO-DE-DATOS.md §3.

-- El texto que se acepta, versionado y con su huella. Nunca se modifica una versión
-- publicada: editar crea otra. Así siempre se sabe QUÉ texto exacto aceptó cada persona.
CREATE TABLE texto_consentimiento (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id bigint NOT NULL REFERENCES organizacion(id),
    tipo            text NOT NULL CHECK (tipo IN ('PROCESO', 'FUTUROS_CONTACTOS')),
    version         text NOT NULL,
    texto           text NOT NULL,
    hash            text NOT NULL,
    publicado_en    timestamptz,
    creado_en       timestamptz NOT NULL DEFAULT now(),
    UNIQUE (organizacion_id, tipo, version)
);

-- Que esta persona aceptó esta versión concreta. Son dos permisos distintos (evaluarme /
-- llamarme para otras oportunidades) y se retiran por separado.
CREATE TABLE consentimiento (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    persona_id              bigint NOT NULL REFERENCES persona(id),
    texto_consentimiento_id bigint NOT NULL REFERENCES texto_consentimiento(id),
    nombre_registrado       text,
    aceptado_en             timestamptz NOT NULL,
    ip                      text,
    id_sesion               text,
    user_agent              text,
    retirado_en             timestamptz,
    creado_en               timestamptz NOT NULL DEFAULT now(),
    UNIQUE (persona_id, texto_consentimiento_id)
);

-- Cuánto se guardan los datos y qué se hace al vencer. Solo una activa por organización.
CREATE TABLE politica_conservacion (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id         bigint NOT NULL REFERENCES organizacion(id),
    meses                   integer NOT NULL,
    accion_al_vencer        text NOT NULL
        CHECK (accion_al_vencer IN ('ELIMINAR', 'ANONIMIZAR', 'RENOVAR_CONSENTIMIENTO')),
    es_activa               boolean NOT NULL DEFAULT false,
    definida_por_usuario_id bigint REFERENCES usuario(id),
    creado_en               timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX politica_conservacion_una_activa
    ON politica_conservacion (organizacion_id) WHERE es_activa;

-- Pedir el borrado y ejecutarlo son dos cosas distintas, con días de por medio.
CREATE TABLE solicitud_borrado (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    persona_id               bigint NOT NULL REFERENCES persona(id),
    motivo                   text,
    solicitado_en            timestamptz NOT NULL,
    ejecutado_en             timestamptz,
    ejecutado_por_usuario_id bigint REFERENCES usuario(id),
    creado_en                timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX consentimiento_texto_idx ON consentimiento (texto_consentimiento_id);
CREATE INDEX solicitud_borrado_persona_idx ON solicitud_borrado (persona_id);
