-- La Solicitud de Talento: por qué hace falta contratar, antes de que exista la vacante.
-- Ver docs/07-DICCIONARIO-DE-DATOS.md §4. Decidido el 15/08: entra en el MVP
-- (toda vacante cuelga de una solicitud aprobada, como pide el documento del cliente).

-- Los dos catálogos cerrados que la solicitud referencia. PK de texto: en los logs y en
-- las consultas se lee DIRECCION, no un 3 que hay que ir a buscar.
CREATE TABLE nivel_puesto (
    codigo               text PRIMARY KEY,
    nombre               text NOT NULL,
    preguntas_banco      integer NOT NULL,
    minutos_objetivo_min integer NOT NULL,
    minutos_objetivo_max integer NOT NULL,
    orden                integer NOT NULL,
    creado_en            timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE familia (
    codigo      text PRIMARY KEY,
    nombre      text NOT NULL,
    descripcion text,
    orden       integer NOT NULL,
    creado_en   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE solicitud_talento (
    id                         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id            bigint NOT NULL REFERENCES organizacion(id),
    origen                     text NOT NULL CHECK (origen IN ('DIRECTA', 'DETECTADA')),
    urgencia                   text NOT NULL CHECK (urgencia IN ('NORMAL', 'PRIORITARIA', 'URGENTE')),
    estado                     text NOT NULL
        CHECK (estado IN ('BORRADOR', 'ABIERTA', 'CON_VACANTE', 'RECHAZADA', 'ARCHIVADA')),
    area_id                    bigint NOT NULL REFERENCES area(id),
    nivel_puesto_codigo        text REFERENCES nivel_puesto(codigo),
    familia_codigo             text REFERENCES familia(codigo),
    resultado_principal        text NOT NULL,
    motivo                     text NOT NULL,
    consecuencia_no_contratar  text NOT NULL,
    requerida_para             date,
    -- Obligatorio en las dos entradas: que la necesidad la pida una persona no la exime
    -- de responder si el trabajo se podría eliminar, automatizar o redistribuir.
    analisis_capacidad         text NOT NULL,
    capacidades_indispensables text,
    capacidades_aprendibles    text,
    modalidad                  text,
    horario                    text,
    compensacion               text,
    solicitada_por_usuario_id  bigint REFERENCES usuario(id),
    responsable_usuario_id     bigint REFERENCES usuario(id),
    creado_en                  timestamptz NOT NULL DEFAULT now()
);

-- Los 3 a 5 resultados del cargo, con su indicador. Que sean entre 3 y 5 lo comprueba
-- el código, no la base.
CREATE TABLE resultado_esperado (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitud_talento_id bigint NOT NULL REFERENCES solicitud_talento(id),
    descripcion          text NOT NULL,
    indicador            text,
    orden                integer NOT NULL,
    creado_en            timestamptz NOT NULL DEFAULT now(),
    UNIQUE (solicitud_talento_id, orden)
);

-- Qué dato hizo que el sistema recomendara la solicitud. Solo existe cuando el origen es
-- DETECTADA. En el hito 1 nace vacía: sin IA no hay sugerencias.
CREATE TABLE evidencia_necesidad (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitud_talento_id bigint NOT NULL REFERENCES solicitud_talento(id),
    tipo                 text NOT NULL
        CHECK (tipo IN ('CARGA', 'RETRASO', 'CALIDAD', 'CAPACIDAD', 'RETRABAJO', 'CRECIMIENTO')),
    descripcion          text NOT NULL,
    valor                text,
    -- Apuntará a ejecucion_ia cuando esa tabla exista (hito 2); mientras, columna suelta
    ejecucion_ia_id      bigint,
    creado_en            timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX solicitud_talento_org_estado_idx ON solicitud_talento (organizacion_id, estado);
CREATE INDEX evidencia_necesidad_solicitud_idx ON evidencia_necesidad (solicitud_talento_id);
