-- Vacantes y la configuración de pesos. Ver docs/07-DICCIONARIO-DE-DATOS.md §5 y §17.
-- La versión de pesos entra desde el hito 1 aunque dos etapas vayan a cero:
-- vacante.version_pesos_id es obligatoria y cada nota queda atada a su versión.

-- Las cinco etapas del embudo. Catálogo cerrado.
CREATE TABLE etapa (
    codigo    text PRIMARY KEY,
    nombre    text NOT NULL,
    orden     integer NOT NULL,
    creado_en timestamptz NOT NULL DEFAULT now()
);

-- Una versión de todos los pesos. Publicada nunca se modifica: editar crea otra.
CREATE TABLE version_pesos (
    id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id           bigint NOT NULL REFERENCES organizacion(id),
    etiqueta                  text NOT NULL,
    estado                    text NOT NULL CHECK (estado IN ('BORRADOR', 'PUBLICADA')),
    publicada_por_usuario_id  bigint REFERENCES usuario(id),
    publicada_en              timestamptz,
    creado_en                 timestamptz NOT NULL DEFAULT now(),
    UNIQUE (organizacion_id, etiqueta)
);

-- Cuánto pesa cada etapa. El nivel salió de la clave: los pesos son iguales para todos
-- y lo que cambia por vacante es a qué versión apunta. Que sumen 100 lo comprueba el
-- código al publicar.
CREATE TABLE peso_etapa (
    version_pesos_id bigint NOT NULL REFERENCES version_pesos(id),
    etapa_codigo     text NOT NULL REFERENCES etapa(codigo),
    peso             numeric(5,2) NOT NULL,
    creado_en        timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (version_pesos_id, etapa_codigo)
);

-- Cómo se reparte el 40% del Perfil Integral. El módulo psicométrico no existe todavía:
-- su 5% se reparte entre los otros dos, y por eso esto son datos y no números en código.
CREATE TABLE peso_componente_perfil (
    version_pesos_id bigint NOT NULL REFERENCES version_pesos(id),
    componente       text NOT NULL CHECK (componente IN ('CV', 'PSICOMETRICO', 'EVALUACION')),
    peso             numeric(5,2) NOT NULL,
    creado_en        timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (version_pesos_id, componente)
);

-- El catálogo de puestos, con su nivel y su familia.
CREATE TABLE puesto (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id     bigint NOT NULL REFERENCES organizacion(id),
    codigo              text NOT NULL,
    nombre              text NOT NULL,
    nivel_puesto_codigo text NOT NULL REFERENCES nivel_puesto(codigo),
    familia_codigo      text NOT NULL REFERENCES familia(codigo),
    es_activo           boolean NOT NULL DEFAULT true,
    creado_en           timestamptz NOT NULL DEFAULT now(),
    UNIQUE (organizacion_id, codigo)
);

-- Una convocatoria concreta. Toda vacante cuelga de una solicitud aprobada.
-- version_plantilla_prueba_id y plantilla_evaluacion_id son columnas sueltas sin FK:
-- sus tablas llegan en los hitos 2 y 3 (la FK se añade entonces, como manda el doc 07
-- para la referencia circular vacante <-> version_plantilla_prueba).
CREATE TABLE vacante (
    id                         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id            bigint NOT NULL REFERENCES organizacion(id),
    solicitud_talento_id       bigint NOT NULL REFERENCES solicitud_talento(id),
    puesto_id                  bigint NOT NULL REFERENCES puesto(id),
    titulo                     text NOT NULL,
    descripcion                text NOT NULL,
    proposito                  text,
    responsabilidades          text,
    requisitos                 text,
    modalidad                  text,
    horario                    text,
    ubicacion                  text,
    compensacion_publica       text,
    tipo_cierre                text NOT NULL CHECK (tipo_cierre IN ('FECHA', 'PLAZAS', 'PERMANENTE')),
    plazas                     integer,
    abre_en                    timestamptz,
    cierra_en                  timestamptz,
    estado                     text NOT NULL CHECK (estado IN ('BORRADOR', 'PUBLICADA', 'CERRADA')),
    nota_minima                numeric(5,2),
    version_pesos_id           bigint NOT NULL REFERENCES version_pesos(id),
    version_plantilla_prueba_id bigint,
    plantilla_evaluacion_id    bigint,
    responsable_usuario_id     bigint NOT NULL REFERENCES usuario(id),
    publicada_en               timestamptz,
    cerrada_en                 timestamptz,
    creado_en                  timestamptz NOT NULL DEFAULT now()
);

-- Lo único que puede detener una postulación sin que intervenga nadie. La regla exacta
-- que se aplicó queda guardada en la transición.
CREATE TABLE requisito_objetivo (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vacante_id  bigint NOT NULL REFERENCES vacante(id),
    descripcion text NOT NULL,
    regla       text NOT NULL,
    es_activo   boolean NOT NULL DEFAULT true,
    creado_en   timestamptz NOT NULL DEFAULT now()
);

-- Del doc 07: las vacantes publicadas son la consulta del portal
CREATE INDEX vacante_org_estado_idx ON vacante (organizacion_id, estado);
CREATE INDEX vacante_solicitud_idx ON vacante (solicitud_talento_id);
CREATE INDEX vacante_responsable_idx ON vacante (responsable_usuario_id);
CREATE INDEX requisito_objetivo_vacante_idx ON requisito_objetivo (vacante_id);
