-- La postulación y su historia. Ver docs/07-DICCIONARIO-DE-DATOS.md §7 y docs/03.

-- Catálogo cerrado de los 18 estados. Solo cambia con una migración: no hay pantalla
-- para inventar estados. Guarda etapa y momento como columnas aparte porque el estado
-- siguiente SE CALCULA (el momento siguiente de esta etapa, o el primero de la que sigue),
-- no se busca en una tabla de transiciones.
CREATE TABLE estado_postulacion (
    codigo        text PRIMARY KEY,
    nombre        text NOT NULL,
    etapa_codigo  text REFERENCES etapa(codigo),
    momento_codigo text
        CHECK (momento_codigo IN ('POR_HABILITAR', 'TURNO_CANDIDATO', 'CALIFICANDO', 'POR_CONFIRMAR')),
    espera_a      text NOT NULL CHECK (espera_a IN ('CANDIDATO', 'SISTEMA', 'TALENTO', 'AREA', 'NADIE')),
    orden         integer NOT NULL,
    es_final      boolean NOT NULL DEFAULT false,
    creado_en     timestamptz NOT NULL DEFAULT now()
);

-- Un usuario en una vacante. Un solo estado a la vez, nunca dos.
-- evaluacion_id queda como columna suelta: su tabla llega en el hito 2.
CREATE TABLE postulacion (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id         bigint NOT NULL REFERENCES organizacion(id),
    uuid                    uuid NOT NULL DEFAULT gen_random_uuid(),
    usuario_id              bigint NOT NULL REFERENCES usuario(id),
    vacante_id              bigint NOT NULL REFERENCES vacante(id),
    estado_codigo           text NOT NULL REFERENCES estado_postulacion(codigo),
    grupo_prioridad         text
        CHECK (grupo_prioridad IN ('ALTA', 'POTENCIAL_CON_RIESGO', 'NO_PRIORIZADO', 'INCOMPATIBLE')),
    motivo_cierre           text
        CHECK (motivo_cierre IN ('REQUISITO_OBJETIVO', 'BARRERA_CRITICA', 'DECISION_ROJA',
                                 'DECISION_PERSONA', 'PASA_A_RESERVA',
                                 'INACTIVIDAD', 'CIERRE_MANUAL', 'RETIRO_CANDIDATO',
                                 'PLAZO_VENCIDO', 'BORRADO_DATOS')),
    evaluacion_id           bigint,
    rondas_evidencia_usadas integer NOT NULL DEFAULT 0,
    movido_en               timestamptz NOT NULL DEFAULT now(),
    creado_en               timestamptz NOT NULL DEFAULT now(),
    UNIQUE (usuario_id, vacante_id),
    UNIQUE (uuid)
);

-- Cada cambio de estado, para siempre. No se modifica ni se borra nunca.
CREATE TABLE transicion_estado (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postulacion_id         bigint NOT NULL REFERENCES postulacion(id),
    estado_anterior_codigo text REFERENCES estado_postulacion(codigo),
    estado_nuevo_codigo    text NOT NULL REFERENCES estado_postulacion(codigo),
    usuario_id             bigint REFERENCES usuario(id),
    rol_id                 bigint REFERENCES rol(id),
    es_sistema             boolean NOT NULL,
    es_por_lote            boolean NOT NULL DEFAULT false,
    motivo                 text,
    ocurrida_en            timestamptz NOT NULL DEFAULT now(),
    creado_en              timestamptz NOT NULL DEFAULT now(),
    -- Toda transición manual exige motivo escrito. Sin excepción.
    CONSTRAINT transicion_motivo_obligatorio
        CHECK (es_sistema OR (motivo IS NOT NULL AND btrim(motivo) <> ''))
);

-- La inmutabilidad no es una convención: la base la impide. Se reutiliza en V8 para auditoria.
CREATE FUNCTION impedir_update_delete() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'La tabla % no admite UPDATE ni DELETE: es un registro inmutable', TG_TABLE_NAME;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER transicion_estado_inmutable
    BEFORE UPDATE OR DELETE ON transicion_estado
    FOR EACH ROW EXECUTE FUNCTION impedir_update_delete();

-- Los índices que el doc 07 exige a mano (PostgreSQL no indexa FKs solo)
CREATE INDEX postulacion_vacante_estado_idx ON postulacion (vacante_id, estado_codigo);
CREATE INDEX postulacion_estado_idx ON postulacion (estado_codigo);
CREATE INDEX postulacion_usuario_idx ON postulacion (usuario_id);
CREATE INDEX postulacion_org_movido_idx ON postulacion (organizacion_id, movido_en);
CREATE INDEX postulacion_grupo_vacante_idx ON postulacion (grupo_prioridad, vacante_id);
CREATE INDEX transicion_estado_postulacion_idx ON transicion_estado (postulacion_id, ocurrida_en);
