-- Archivos y currículum. Ver docs/07-DICCIONARIO-DE-DATOS.md §9 y §19.

-- Los archivos viven fuera de la base; aquí solo está su ruta. La ruta se anula al
-- borrar el archivo (anonimización), pero la fila se conserva.
CREATE TABLE archivo (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id bigint NOT NULL REFERENCES organizacion(id),
    ruta            text,
    nombre_original text,
    tamano          bigint,
    tipo            text,
    subido_en       timestamptz NOT NULL DEFAULT now(),
    borrado_en      timestamptz,
    creado_en       timestamptz NOT NULL DEFAULT now()
);

-- El currículum de una postulación, en sus dos versiones: lo que subió (se borra al
-- anonimizar) y la versión sin datos personales (lo único que verá la máquina, hito 2).
-- resultado_orgulloso: el texto obligatorio del formulario de postular («cuéntanos qué
-- cambió gracias a tu trabajo»). Vive aquí porque es evidencia 1:1 con la postulación
-- y se vacía junto al resto del CV al anonimizar.
CREATE TABLE cv (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    postulacion_id         bigint NOT NULL REFERENCES postulacion(id),
    archivo_original_id    bigint REFERENCES archivo(id),
    archivo_anonimizado_id bigint REFERENCES archivo(id),
    texto_extraido         text,
    resultado_orgulloso    text,
    creado_en              timestamptz NOT NULL DEFAULT now(),
    UNIQUE (postulacion_id)
);

-- Portafolio, repositorio, proyectos.
CREATE TABLE enlace_cv (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cv_id     bigint NOT NULL REFERENCES cv(id),
    url       text NOT NULL,
    tipo      text CHECK (tipo IN ('PORTAFOLIO', 'REPOSITORIO', 'PUBLICACION', 'PRODUCTO', 'OTRO')),
    creado_en timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX enlace_cv_cv_idx ON enlace_cv (cv_id);
