-- Parámetros, correos y auditoría. Ver docs/07-DICCIONARIO-DE-DATOS.md §17 y §19.

-- Los valores sueltos que Renaser cambia sin programar.
CREATE TABLE parametro (
    id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id           bigint NOT NULL REFERENCES organizacion(id),
    codigo                    text NOT NULL,
    valor                     text NOT NULL,
    tipo                      text NOT NULL CHECK (tipo IN ('ENTERO', 'TEXTO', 'BOOLEANO', 'LISTA')),
    descripcion               text NOT NULL,
    modificado_por_usuario_id bigint REFERENCES usuario(id),
    modificado_en             timestamptz,
    creado_en                 timestamptz NOT NULL DEFAULT now(),
    UNIQUE (organizacion_id, codigo)
);

-- Los textos que se envían, versionados. Editar crea una versión nueva.
CREATE TABLE plantilla_correo (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id bigint NOT NULL REFERENCES organizacion(id),
    codigo          text NOT NULL,
    version         integer NOT NULL,
    asunto          text NOT NULL,
    cuerpo          text NOT NULL,
    es_activa       boolean NOT NULL DEFAULT false,
    creado_en       timestamptz NOT NULL DEFAULT now(),
    UNIQUE (organizacion_id, codigo, version)
);

-- A quién, cuándo y QUÉ decía: el cuerpo ya armado, no la plantilla. Si un candidato
-- reclama meses después, se lee exactamente lo que se le dijo. Guarda código y versión
-- de la plantilla como valores, sin FK: el dato no debe cambiar bajo los pies.
CREATE TABLE correo_enviado (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id              bigint NOT NULL REFERENCES usuario(id),
    plantilla_correo_codigo text NOT NULL,
    version_plantilla       integer NOT NULL,
    asunto                  text NOT NULL,
    cuerpo                  text NOT NULL,
    canal                   text NOT NULL DEFAULT 'CORREO',
    estado_entrega          text,
    enviado_en              timestamptz NOT NULL DEFAULT now(),
    creado_en               timestamptz NOT NULL DEFAULT now()
);

-- Toda acción que cambia una decisión. No se modifica ni se borra, y eso no es
-- configurable: no existe la casilla para permitirlo.
CREATE TABLE auditoria (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id bigint NOT NULL REFERENCES organizacion(id),
    usuario_id      bigint REFERENCES usuario(id),
    rol_id          bigint REFERENCES rol(id),
    accion          text NOT NULL,
    entidad         text NOT NULL,
    entidad_id      bigint,
    valor_anterior  jsonb,
    valor_nuevo     jsonb,
    motivo          text,
    ocurrida_en     timestamptz NOT NULL DEFAULT now(),
    creado_en       timestamptz NOT NULL DEFAULT now()
);

-- Reutiliza la función creada en V6
CREATE TRIGGER auditoria_inmutable
    BEFORE UPDATE OR DELETE ON auditoria
    FOR EACH ROW EXECUTE FUNCTION impedir_update_delete();

CREATE INDEX auditoria_entidad_idx ON auditoria (entidad, entidad_id);
CREATE INDEX auditoria_org_fecha_idx ON auditoria (organizacion_id, ocurrida_en);
CREATE INDEX correo_enviado_usuario_idx ON correo_enviado (usuario_id);
